const image =
    'data:image/svg+xml,' +
    encodeURIComponent(
        '<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="700">' +
            '<rect width="1200" height="700" fill="#cabc9c"/>' +
            '<circle cx="970" cy="260" r="170" fill="#e9dec8"/>' +
            '<path d="M680 600L830 100 1120 610" fill="#b29b74"/></svg>',
    );
const asset = { id: 'fixture-asset', preview: image };
const variant = {
    id: 'variant-1',
    name: '日常随行杯',
    sku: 'QA-CUP',
    priceWithTax: 2990,
    currencyCode: 'MYR',
    stockLevel: 'IN_STOCK',
    saleableStockLevel: 12,
    featuredAsset: asset,
    product: { id: 'product-1', name: '日常随行杯', featuredAsset: asset },
    customFields: { fulfillmentType: 'physical' },
};
const product = {
    id: 'product-1',
    createdAt: '2026-09-01T00:00:00Z',
    name: '日常随行杯',
    slug: 'qa-cup',
    description: '<p>用于皮肤验收的示例商品。</p>',
    featuredAsset: asset,
    assets: [asset],
    collections: [],
    variants: [variant],
    packaging: null,
    customFields: {
        fulfillmentType: 'physical',
        refundPolicy: 'MERCHANT_REVIEW',
        manualDeliverySlaMinutes: 0,
    },
};
const collectionChild = {
    id: 'collection-cups',
    name: '随行杯',
    slug: 'cups',
    description: '',
    position: 0,
    parentId: 'collection-daily',
    featuredAsset: asset,
    children: [],
};
const collection = {
    id: 'collection-daily',
    name: '日常用品',
    slug: 'daily',
    description: '',
    position: 0,
    parentId: 'root',
    featuredAsset: asset,
    children: [collectionChild],
};
const order = {
    id: 'order-1',
    code: 'QA0001',
    state: 'AddingItems',
    totalQuantity: 1,
    subTotalWithTax: 2990,
    shippingWithTax: 0,
    totalWithTax: 2990,
    currencyCode: 'MYR',
    lines: [
        {
            id: 'line-1',
            quantity: 1,
            linePriceWithTax: 2990,
            proratedUnitPriceWithTax: 2990,
            productVariant: variant,
            customFields: { fulfillmentTypeSnapshot: 'physical' },
        },
    ],
    discounts: [],
    taxSummary: [],
    couponCodes: [],
    customFields: { customerNote: null },
    shippingLines: [],
    payments: [],
    checkoutFulfillment: {
        fulfillmentType: 'PHYSICAL',
        containsPhysicalProducts: true,
        containsDigitalProducts: false,
        requiresShippingAddress: true,
        requiresShippingMethod: true,
    },
};
const cart = {
    id: 'cart-1',
    revision: 1,
    state: 'OPEN',
    projectedRevision: 1,
    totalQuantity: 1,
    selectedLineCount: 1,
    selectedQuantity: 1,
    selectionState: 'ALL',
    lines: [{ id: 'cart-line', quantity: 1, selected: true, available: true, productVariant: variant }],
    checkoutOrder: order,
};
const customer = {
    id: 'customer-1',
    firstName: '测试',
    lastName: '用户',
    emailAddress: 'qa@example.invalid',
    phoneNumber: null,
    addresses: [],
    orders: { items: [], totalItems: 0 },
};
const block = {
    id: 'hero-1',
    code: 'qa-hero',
    type: 'HERO',
    enabled: true,
    position: 0,
    startsAt: null,
    endsAt: null,
    imageUrl: image,
    backgroundColor: '#102030',
    textColor: '#ffffff',
    targetType: 'PAGE',
    targetValue: '/category',
    settings: { accentColor: '#67e8f9' },
    title: '好物相伴，从容生活',
    subtitle: '日常甄选',
    body: '这是本地皮肤验收内容，图片与真实店铺无关。',
    ctaLabel: '查看好物',
    items: [],
};
const quickLinksBlock = {
    id: 'qa-quick-links',
    code: 'homepage-quick-links',
    type: 'QUICK_LINKS',
    enabled: true,
    position: 1,
    startsAt: null,
    endsAt: null,
    imageUrl: null,
    backgroundColor: null,
    textColor: null,
    targetType: 'NONE',
    targetValue: null,
    settings: {},
    title: '快捷入口',
    subtitle: '',
    body: '',
    ctaLabel: '',
    items: [
        ['商品分类', '浏览店铺当前开放的商品分类', 'CATEGORY', null],
        ['智能服务', '查看店铺提供的工具与服务', 'PAGE', 'services'],
        ['帮助中心', '订单与服务遇到问题，查看帮助', 'SUPPORT', null],
        ['优惠中心', '查看当前可领取的店铺优惠', 'COUPON', null],
        ['我的订单', '查询订单状态与物流进度', 'PAGE', 'orders'],
    ].map(([label, description, targetType, targetValue], position) => ({
        id: `qa-quick-link-${position}`,
        enabled: true,
        position,
        imageUrl: null,
        targetType,
        targetValue,
        settings: {},
        label,
        description,
    })),
};
const servicesBlock = {
    id: 'qa-services',
    code: 'storefront-client-plugins',
    type: 'CLIENT_PLUGINS',
    enabled: true,
    position: 10_001,
    startsAt: null,
    endsAt: null,
    imageUrl: null,
    backgroundColor: null,
    textColor: null,
    targetType: 'NONE',
    targetValue: null,
    settings: { businessServicesCopyVersion: 1 },
    title: '店铺服务',
    subtitle: '',
    body: '在这里使用店铺工具与服务。',
    ctaLabel: '',
    items: [
        'two-factor-code-tool',
        'icloud-mail-query-entry',
        'ai-image-studio-entry',
        'category-coupon-entry',
        'category-support-entry',
    ].map((pluginCode, position) => ({
        id: `qa-service-${position}`,
        enabled: true,
        position,
        imageUrl: null,
        targetType: 'NONE',
        targetValue: null,
        settings: {
            pluginCode,
            placement: 'BUSINESS_SERVICES_MAIN',
            categoryScope: 'ALL',
            categoryIds: [],
            includeChildren: true,
        },
        label: pluginCode,
        description: '',
    })),
};
const model = {
    id: 'model-1',
    code: 'GEMINI_FLASH',
    displayNameZh: 'Gemini 3.1 Flash Image',
    displayNameEn: 'Gemini 3.1 Flash Image',
    descriptionZh: '快速生成图片',
    descriptionEn: 'Image creation',
    officialModelId: 'gemini-3.1-flash-image',
    unitPrice: 30,
    unitPrice2K: 30,
    unitPrice4K: 30,
    resolutionOptions: [{ resolution: '1K', unitPrice: 30, supportedAspectRatios: ['1:1'] }],
    currencyCode: 'MYR',
    position: 0,
    isDefault: true,
    healthStatus: 'HEALTHY',
    freeImageEnabled: false,
    dailyFreeImageLimit: 0,
    dailyFreeImageUnlimited: false,
    paidAfterFreeEnabled: true,
    dailyGenerationSafetyLimit: 100,
};
const quotaWindow = {
    limit: 10,
    unlimited: false,
    reserved: 0,
    consumed: 0,
    remaining: 10,
    windowEndsAt: '2030-01-01T00:00:00Z',
};
export function fixtureData(presetId = 'modern-oriental', signedIn = true) {
    return {
        storefrontVisualPreset: { channelId: 'qa-channel', presetId, revision: 'qa-1' },
        activeChannel: {
            id: 'qa-channel',
            code: 'qa-channel',
            defaultLanguageCode: 'zh_Hans',
            defaultCurrencyCode: 'MYR',
            customFields: { storefrontNameZh: '店铺皮肤验收', storefrontNameEn: 'Visual preset QA' },
        },
        availableCountries: [{ code: 'MY', name: 'Malaysia' }],
        storefrontBranding: {
            logoUrl: null,
            description: '本地测试数据',
            backgroundColor: '#070b14',
            primaryColor: '#3558aa',
            accentColor: '#22d3ee',
            highlightColor: '#8b5cf6',
        },
        storefrontCurrencyConfiguration: {
            defaultCurrencyCode: 'MYR',
            availableCurrencyCodes: ['MYR'],
            selectorEnabled: false,
            cnyToMyrRate: 0.6,
            usdtDisplayEnabled: false,
        },
        storefrontContentSettings: {
            heroAutoplayIntervalSeconds: 5,
            configuredBlockTypes: ['HERO', 'AUTH_LOGIN', 'AUTH_REGISTER'],
        },
        storefrontContent: [block, quickLinksBlock, servicesBlock],
        activeStorefrontFlashSales: [],
        activeSystemAnnouncements: [],
        products: { items: [product], totalItems: 1 },
        product,
        collections: { items: [collection], totalItems: 1 },
        storefrontCatalog: { items: [product], totalItems: 1 },
        storefrontProductSales: [],
        activeStoreCommerceMode: 'HYBRID',
        storefrontCart: cart,
        activeCustomer: signedIn ? customer : null,
        myCustomerAvatar: null,
        activeStorefrontCoupons: [],
        myStoreCoupons: [],
        myStoreCouponUsageRecords: [],
        myDeliveryEmails: [],
        eligibleShippingMethods: [],
        eligiblePaymentMethods: [],
        myReferralOverview: null,
        storefrontReferralProgram: null,
        imageStudioConfig: {
            enabled: true,
            promptOptimizationEnabled: true,
            promptOptimizerModelIds: ['gpt-5'],
            promptRateLimitPerMinute: 10,
            promptDailyFreeLimit: 10,
            promptDailyFreeUnlimited: false,
            paidPromptOptimizationEnabled: false,
            paidPromptOptimizationPrice: 0,
            paidPromptOptimizationCurrencyCode: 'MYR',
            defaultModelCode: 'GEMINI_FLASH',
            termsVersion: 'qa',
            termsZh: '仅供本地验收',
            termsEn: 'Local QA',
            outputRetentionDays: 30,
            referenceRetentionHours: 24,
            maxReferenceBytes: 10000000,
            maxReferencePixels: 16000000,
            maxQuantity: 4,
            models: [model],
        },
        imageStudioWallet: { availableBalance: 1000, currencyCode: 'MYR' },
        imagePromptQuotaStatus: {
            minute: quotaWindow,
            daily: quotaWindow,
            paidEnabled: false,
            paidPrice: 0,
            currencyCode: 'MYR',
        },
        imageModelQuotaStatus: [],
        myImageGenerationJobs: { items: [], totalItems: 0 },
        productReviews: { items: [], totalItems: 0 },
        productReviewSummary: { averageRating: 0, totalReviews: 0 },
    };
}
