/* eslint-disable max-len -- Tailwind utility maps are atomic strings consumed by the extractor. */
/**
 * Tailwind utility maps for the remaining large commerce pages.
 *
 * Semantic keys stay in the DOM as stable state/descendant hooks; their visual rules are
 * emitted as Tailwind arbitrary utilities so page-specific declarations can leave styles.css.
 */
type PageStyleMap = Readonly<Record<string, string>>;

export function pageClassName(styles: PageStyleMap, className?: string | false | null): string | undefined {
    if (!className) return undefined;
    return className
        .split(/\s+/)
        .filter(Boolean)
        .flatMap(token => [token, styles[token] ?? ''])
        .filter(Boolean)
        .join(' ');
}

export const orderPageStyles: PageStyleMap = {
    'after-sales-cancel':
        '[min-height:40px] [margin-top:12px] [padding:0_14px] [border:1px_solid_var(--line)] [border-radius:7px] [background:white]',
    'after-sales-field':
        '[&>span]:[margin-bottom:7px] [&>span]:[font-weight:var(--font-weight-medium)] [&_small]:[margin-top:3px] [&_small]:[color:var(--muted)] [margin-top:14px] [display:block] [&>span]:[display:block] [&>small]:[display:block] [&_select]:[width:100%] [&_select]:[padding:10px_11px] [&_select]:[border:1px_solid_var(--line)] [&_select]:[border-radius:7px] [&_select]:[background:white] [&_select]:[color:var(--text)] [&_select]:[font:inherit] [&_textarea]:[width:100%] [&_textarea]:[padding:10px_11px] [&_textarea]:[border:1px_solid_var(--line)] [&_textarea]:[border-radius:7px] [&_textarea]:[background:white] [&_textarea]:[color:var(--text)] [&_textarea]:[font:inherit] [&_select]:[min-height:44px] [&_textarea]:[min-height:112px] [&_textarea]:[resize:vertical]',
    'after-sales-items':
        '[padding:10px_0] [display:grid] [gap:7px] [&_span]:[display:block] [&_strong]:[display:block] [&_small]:[display:block] [&_small]:[margin-top:2px] [&_small]:[color:var(--muted)]',
    'after-sales-line-selection':
        '[margin:0_0_14px] [padding:0] [border:0] [&_legend]:[margin-bottom:7px] [&_legend]:[font-weight:var(--font-weight-medium)] [&>div]:[min-height:58px] [&>div]:[padding:8px_0] [&>div]:[border-bottom:1px_solid_var(--line)] [&>div]:[display:flex] [&>div]:[align-items:center] [&>div]:[justify-content:space-between] [&>div]:[gap:10px] [&>.inline-notice]:[min-height:auto] [&>.inline-notice]:[margin-top:10px] [&>.inline-notice]:[padding:10px] [&>.inline-notice]:[border:1px_solid_#f0d8aa] [&>.inline-notice]:[border-radius:7px] [&>.inline-notice]:[background:#fff9ec] [&>.inline-notice]:[color:#815f1c] [&>.inline-notice]:[font-size:12px] [&>.inline-notice]:[line-height:1.5] [&>div>label:first-child]:[min-width:0] [&>div>label:first-child]:[flex:1] [&>div>label:first-child]:[display:flex] [&>div>label:first-child]:[align-items:center] [&>div>label:first-child]:[gap:10px] [&_label_span]:[min-width:0] [&_label_span]:[display:block] [&_label_strong]:[min-width:0] [&_label_strong]:[display:block] [&_label_small]:[min-width:0] [&_label_small]:[display:block] [&_label_strong]:[overflow:hidden] [&_label_strong]:[white-space:nowrap] [&_label_strong]:[text-overflow:ellipsis] [&_label_small]:[margin-top:3px] [&_label_small]:[color:var(--muted)]',
    'after-sales-list': '[padding:9px_0_28px]',
    'after-sales-order-link':
        '[display:flex] [align-items:center] [width:100%] [min-height:42px] [margin-top:10px] [padding:0] [justify-content:space-between] [border:0] [border-top:1px_solid_var(--line)] [border-bottom:1px_solid_var(--line)] [background:transparent] [&_svg]:[width:17px] [&_svg]:[height:17px] [&_svg]:[color:var(--muted)]',
    'after-sales-quantity':
        '[display:flex] [align-items:center] [gap:6px] [&_input]:[width:58px] [&_input]:[height:38px] [&_input]:[padding:0_6px] [&_input]:[border:1px_solid_var(--line)] [&_input]:[border-radius:6px]',
    'after-sales-request-total':
        '[margin-top:16px] [padding:12px] [border-radius:7px] [background:var(--soft)] [display:grid] [grid-template-columns:minmax(0,_1fr)_auto] [gap:5px_12px] [&_strong]:[color:var(--accent)] [&_small]:[grid-column:1_/_-1] [&_small]:[color:var(--muted)]',
    'after-sales-sheet': '[&>form]:[padding:16px_14px_calc(18px_+_var(--safe-bottom))]',
    'after-sales-submit-actions':
        '[margin-top:16px] [display:grid] [grid-template-columns:repeat(2,_minmax(0,_1fr))] [gap:10px] [&_button]:[min-height:46px] [&_button]:[padding:0_14px] [&_button]:[border:1px_solid_var(--line)] [&_button]:[border-radius:7px] [&_button]:[background:white] [&_button]:[font-weight:var(--font-weight-semibold)]',
    'auto-card-delivery-panel':
        '[border-left:3px_solid_#2f8f68] [&_article_em]:[max-width:48%] [&_article_em]:[color:#246b50] [&_article_em]:[font-weight:600] [&_article_em]:[text-align:right]',
    'digital-delivery-panel':
        '[margin-top:9px] [padding:16px_14px] [background:white] [&>header]:[padding-bottom:12px] [&>header]:[border-bottom:1px_solid_var(--line)] [&>header>div]:[display:flex] [&>header>div]:[align-items:center] [&>header>div]:[gap:8px] [&>header_svg]:[width:19px] [&>header_svg]:[height:19px] [&>header_svg]:[color:var(--accent)] [&>header_small]:[display:block] [&>header_small]:[margin-top:5px] [&>header_small]:[color:var(--muted)] [&>header_small]:[line-height:1.45] [&>div>article]:[min-height:62px] [&>div>article]:[padding:10px_0] [&>div>article]:[border-bottom:1px_solid_var(--line)] [&>div>article]:[display:flex] [&>div>article]:[align-items:center] [&>div>article]:[justify-content:space-between] [&>div>article]:[gap:12px] [&>div>article:last-child]:[border-bottom:0] [&_article_span]:[min-width:0] [&_article_span]:[display:block] [&_article_strong]:[min-width:0] [&_article_strong]:[display:block] [&_article_small]:[min-width:0] [&_article_small]:[display:block] [&_article_small]:[margin-top:3px] [&_article_small]:[color:var(--muted)] [&_article_small]:[font-size:12px] [&_article_small]:[font-style:normal] [&_article_em]:[margin-top:3px] [&_article_em]:[color:var(--muted)] [&_article_em]:[font-size:12px] [&_article_em]:[font-style:normal] [&_article_a]:[min-height:38px] [&_article_a]:[padding:0_13px] [&_article_a]:[border-radius:7px] [&_article_a]:[background:var(--accent)] [&_article_a]:[color:white] [&_article_a]:[display:inline-flex] [&_article_a]:[align-items:center] [&_article_a]:[gap:6px] [&_article_a]:[flex:0_0_auto] [&_article_a]:[text-decoration:none] [&_article_a_svg]:[width:16px] [&_article_a_svg]:[height:16px]',
    'logistics-detail':
        '[margin-top:4px] [&>summary]:[min-height:46px] [&>summary]:[margin:0_12px] [&>summary]:[padding:0_2px] [&>summary]:[cursor:pointer] [&>summary]:[color:var(--accent)] [&>summary]:[display:flex] [&>summary]:[align-items:center] [&>summary]:[justify-content:space-between] [&>summary]:[list-style:none] [&>summary::-webkit-details-marker]:[display:none] [&>summary_svg]:[width:17px] [&>summary_svg]:[height:17px] [&>summary_svg]:[transition:transform_180ms_ease] [&[open]>summary_svg]:[transform:rotate(90deg)] [&>summary:focus-visible]:[outline:2px_solid_color-mix(in_srgb,_var(--accent)_52%,_white)] [&>summary:focus-visible]:[outline-offset:-2px] max-[370px]:[&>summary]:[margin-right:10px] max-[370px]:[&>summary]:[margin-left:10px] lg:[&>summary]:[margin-right:18px] lg:[&>summary]:[margin-left:18px]',
    'logistics-detail-body':
        '[padding:0_12px_12px] [&>dl]:[margin:0] [&>dl]:[padding:10px_0] [&>dl]:[border-top:1px_solid_var(--line)] [&>dl]:[display:grid] [&>dl]:[gap:7px] [&>dl>div]:[display:grid] [&>dl>div]:[grid-template-columns:74px_minmax(0,_1fr)] [&>dl>div]:[gap:8px] [&_dt]:[color:var(--muted)] [&_dd]:[min-width:0] [&_dd]:[margin:0] [&_dd]:[overflow-wrap:anywhere] [&_dd]:[text-align:right] [&_dd]:[font-variant-numeric:tabular-nums] max-[370px]:[padding-right:10px] max-[370px]:[padding-left:10px] lg:[padding-right:18px] lg:[padding-left:18px]',
    'logistics-list':
        '[padding:10px_10px_30px] [display:grid] [gap:10px] [&>.empty-state]:[margin-top:10px] [&>.empty-state]:[background:white] max-[370px]:[padding-right:8px] max-[370px]:[padding-left:8px] lg:[width:100%] lg:[max-width:760px] lg:[margin-right:auto] lg:[margin-left:auto] lg:[padding:20px_0_48px] lg:[gap:16px]',
    'logistics-load-more': '[width:100%]',
    'logistics-modular-hub':
        '[padding:12px_12px_6px] [display:flex] [flex-direction:column] [gap:10px] [background:transparent]',
    'logistics-order-link':
        '[width:100%] [min-height:44px] [padding:0_10px] [border:1px_solid_var(--line)] [border-radius:8px] [background:white] [display:flex] [align-items:center] [justify-content:space-between] [gap:8px] [&>span:first-child]:[min-width:0] [&>span:first-child]:[overflow:hidden] [&>span:first-child]:[color:var(--muted)] [&>span:first-child]:[white-space:nowrap] [&>span:first-child]:[text-overflow:ellipsis] [&>span:last-child]:[flex:none] [&>span:last-child]:[color:var(--accent)] [&>span:last-child]:[display:inline-flex] [&>span:last-child]:[align-items:center] [&>span:last-child]:[gap:2px] [&>span:last-child]:[font-weight:var(--font-weight-medium)] [&_svg]:[width:16px] [&_svg]:[height:16px] [&:active]:[transform:scale(0.985)]',
    'logistics-page':
        '[--page-surface:var(--paper)] [&>.subpage-header]:[border-bottom-color:color-mix(in_srgb,_var(--accent)_10%,_var(--line))] [&>.subpage-header]:[background:rgba(255,_255,_255,_0.98)] [&>.empty-state]:[margin-top:10px] [&>.empty-state]:[background:white] lg:[&>.empty-state]:[width:100%] lg:[&>.empty-state]:[max-width:760px] lg:[&>.empty-state]:[margin-right:auto] lg:[&>.empty-state]:[margin-left:auto] lg:[&>.list-skeleton]:[width:100%] lg:[&>.list-skeleton]:[max-width:760px] lg:[&>.list-skeleton]:[margin-right:auto] lg:[&>.list-skeleton]:[margin-left:auto]',
    'logistics-product':
        '[min-height:72px] [padding:9px] [display:grid] [grid-template-columns:54px_minmax(0,_1fr)_auto] [align-items:center] [gap:10px] [&+.logistics-product]:[border-top:1px_solid_var(--line)] [&>img]:[width:54px] [&>img]:[height:54px] [&>img]:[border-radius:8px] [&>img]:[background:var(--product-media-bg)] [&>img]:[object-fit:contain] [&>.responsive-picture>img]:[width:54px] [&>.responsive-picture>img]:[height:54px] [&>.responsive-picture>img]:[border-radius:8px] [&>.responsive-picture>img]:[background:var(--product-media-bg)] [&>.responsive-picture>img]:[object-fit:contain] [&>.image-placeholder]:[width:54px] [&>.image-placeholder]:[height:54px] [&>.image-placeholder]:[border-radius:8px] [&>.image-placeholder]:[background:var(--product-media-bg)] [&>.image-placeholder]:[object-fit:contain] [&>span]:[min-width:0] [&_strong]:[display:block] [&_small]:[display:block] [&_strong]:[overflow:hidden] [&_strong]:[font-weight:var(--font-weight-medium)] [&_strong]:[white-space:nowrap] [&_strong]:[text-overflow:ellipsis] [&_small]:[margin-top:4px] [&_small]:[color:var(--muted)] [&>b]:[color:var(--muted)] [&>b]:[font-weight:var(--font-weight-medium)] [&>b]:[font-variant-numeric:tabular-nums]',
    'logistics-products':
        '[margin:0_12px] [overflow:hidden] [border-radius:10px] [background:var(--soft)] max-[370px]:[margin-right:10px] max-[370px]:[margin-left:10px] lg:[margin-right:18px] lg:[margin-left:18px]',
    'logistics-service-strip':
        '[display:flex] [align-items:center] [justify-content:space-between] [padding:8px_12px] [border-radius:10px] [background:rgba(255,_255,_255,_0.7)] [border:1px_dashed_#e2e8f0] [backdrop-filter:blur(8px)]',
    'logistics-stats-grid': '[display:grid] [grid-template-columns:repeat(4,_1fr)] [gap:8px]',
    'logistics-status-icon':
        '[width:34px] [height:34px] [border-radius:9px] [background:var(--accent-soft)] [color:var(--accent)] [display:grid] [place-items:center] [&_svg]:[width:18px] [&_svg]:[height:18px] [.logistics-card.is-delivered_&]:[background:color-mix(in_srgb,_var(--success)_10%,_white)] [.logistics-card.is-delivered_&]:[color:var(--success)] [.logistics-card.is-cancelled_&]:[background:var(--soft)] [.logistics-card.is-cancelled_&]:[color:var(--muted)] max-[370px]:[width:32px] max-[370px]:[height:32px]',
    'logistics-timeline':
        "[margin:0] [padding:8px_4px_2px] [list-style:none] [&_li]:[min-height:52px] [&_li]:[position:relative] [&_li]:[display:grid] [&_li]:[grid-template-columns:14px_minmax(0,_1fr)] [&_li]:[gap:10px] [&_li:not(:last-child)::before]:[width:1px] [&_li:not(:last-child)::before]:[position:absolute] [&_li:not(:last-child)::before]:[top:11px] [&_li:not(:last-child)::before]:[bottom:0] [&_li:not(:last-child)::before]:[left:6px] [&_li:not(:last-child)::before]:[background:var(--line)] [&_li:not(:last-child)::before]:[content:''] [&_li>span]:[width:9px] [&_li>span]:[height:9px] [&_li>span]:[margin-top:4px] [&_li>span]:[position:relative] [&_li>span]:[z-index:1] [&_li>span]:[border-radius:50%] [&_li>span]:[background:#c8cfcb] [&_li.is-current>span]:[background:var(--accent)] [&_li.is-current>span]:[box-shadow:0_0_0_4px_var(--accent-soft)] [&_strong]:[display:block] [&_small]:[display:block] [&_strong]:[font-weight:var(--font-weight-medium)] [&_small]:[margin-top:4px] [&_small]:[color:var(--muted)] [&_small]:[font-variant-numeric:tabular-nums]",
    'order-btn':
        '[min-height:30px] [padding:0_12px] [border-radius:999px] [font-size:12.5px] [font-weight:600] [display:inline-flex] [align-items:center] [justify-content:center] [cursor:pointer] [transition:all_160ms_ease] [white-space:nowrap] [&.secondary-btn]:[border:1px_solid_rgba(203,_213,_225,_0.8)] [&.secondary-btn]:[background:white] [&.secondary-btn]:[color:var(--text)] [&.secondary-btn:hover]:[background:var(--soft)] [&.secondary-btn:hover]:[border-color:var(--muted)] [&.primary-btn]:[border:1px_solid_transparent] [&.primary-btn]:[background:var(--accent)] [&.primary-btn]:[color:white] [&.primary-btn]:[font-weight:var(--font-weight-semibold)] [&.primary-btn]:[box-shadow:0_2px_6px_rgba(37,_99,_235,_0.2)] [&.primary-btn:hover]:[background:var(--accent-hover)]',
    'order-cancel-actions':
        '[&_.danger-action]:[border-color:rgba(192,_57,_43,_0.34)] [&_.danger-action]:[color:#a93226] [margin-top:16px] [display:grid] [grid-template-columns:repeat(2,_minmax(0,_1fr))] [gap:10px] [&_button]:[min-height:46px] [&_button]:[padding:0_14px] [&_button]:[border:1px_solid_var(--line)] [&_button]:[border-radius:7px] [&_button]:[background:white] [&_button]:[font-weight:var(--font-weight-semibold)]',
    'order-cancel-sheet':
        '[&>form]:[padding:18px_14px_calc(18px_+_var(--safe-bottom))] [&_p]:[margin:0_0_16px] [&_p]:[color:var(--muted)] [&_p]:[line-height:1.6] [&_label]:[display:block] [&_label>span]:[display:block] [&_label>span]:[margin-bottom:7px] [&_label>span]:[font-weight:var(--font-weight-medium)] [&_textarea]:[width:100%] [&_textarea]:[min-height:108px] [&_textarea]:[padding:11px_12px] [&_textarea]:[resize:vertical] [&_textarea]:[border:1px_solid_var(--line)] [&_textarea]:[border-radius:7px] [&_textarea]:[background:white] [&_textarea]:[color:var(--text)] [&_textarea]:[font:inherit] [&_form>small]:[margin-top:5px] [&_form>small]:[color:var(--muted)] [&_form>small]:[display:block] [&_form>small]:[text-align:right]',
    'order-card-buttons':
        '[display:flex] [align-items:center] [justify-content:flex-end] [gap:6px] [flex-shrink:0]',
    'order-card-footer':
        '[display:flex] [align-items:center] [justify-content:space-between] [gap:8px] [padding-top:10px] [border-top:1px_solid_rgba(241,_245,_249,_0.9)]',
    'order-card-header':
        '[min-height:28px] [display:flex] [align-items:center] [justify-content:space-between] [gap:8px] [padding-bottom:10px] [border-bottom:1px_solid_rgba(241,_245,_249,_0.9)]',
    'order-card-product':
        '[width:100%] [min-height:76px] [padding:0] [border:0] [background:transparent] [display:grid] [grid-template-columns:76px_minmax(0,_1fr)_auto] [align-items:start] [gap:12px] [text-align:left] [cursor:pointer] [&>img]:[width:76px] [&>img]:[height:76px] [&>img]:[border-radius:10px] [&>img]:[background:var(--product-media-bg)] [&>img]:[object-fit:cover] [&>img]:[border:1px_solid_rgba(226,_232,_240,_0.7)] [&>.responsive-picture>img]:[width:76px] [&>.responsive-picture>img]:[height:76px] [&>.responsive-picture>img]:[border-radius:10px] [&>.responsive-picture>img]:[background:var(--product-media-bg)] [&>.responsive-picture>img]:[object-fit:cover] [&>.responsive-picture>img]:[border:1px_solid_rgba(226,_232,_240,_0.7)] [&>.image-placeholder]:[width:76px] [&>.image-placeholder]:[height:76px] [&>.image-placeholder]:[border-radius:10px] [&>.image-placeholder]:[background:var(--product-media-bg)] [&>.image-placeholder]:[object-fit:cover] [&>.image-placeholder]:[border:1px_solid_rgba(226,_232,_240,_0.7)]',
    'order-card-store-btn':
        '[min-width:0] [min-height:28px] [padding:0] [border:0] [background:transparent] [display:inline-flex] [align-items:center] [gap:6px] [cursor:pointer] [&_strong]:[font-size:15px] [&_strong]:[font-weight:var(--font-weight-bold)] [&_strong]:[color:var(--text)] [&_strong]:[overflow:hidden] [&_strong]:[white-space:nowrap] [&_strong]:[text-overflow:ellipsis] [&_svg:last-child]:[width:15px] [&_svg:last-child]:[height:15px] [&_svg:last-child]:[color:var(--muted)]',
    'order-card-store-icon': '[width:17px] [height:17px] [color:var(--accent)] [flex-shrink:0]',
    'order-detail-actions':
        '[width:min(100%,_var(--app-width))] [min-height:calc(var(--order-detail-action-bar-height)_+_var(--safe-bottom))] [padding:9px_10px_calc(9px_+_var(--safe-bottom))] [position:fixed] [z-index:22] [right:0] [bottom:0] [left:50%] [border-top:1px_solid_var(--line)] [background:rgba(255,_255,_255,_0.98)] [display:flex] [justify-content:flex-end] [gap:8px] [transform:translateX(-50%)] [&_button]:[min-width:108px] [&_button]:[height:48px] [&_button]:[padding:0_14px] [&_button]:[border:1px_solid_var(--line)] [&_button]:[border-radius:7px] [&_button]:[background:white] [&_.danger-action]:[border-color:rgba(192,_57,_43,_0.34)] [&_.danger-action]:[color:#a93226] lg:[width:min(calc(100%_-_64px),_var(--desktop-shell-width))] lg:[right:auto] lg:[bottom:24px] lg:[left:50%] lg:[border:1px_solid_var(--line)] lg:[border-radius:8px] lg:[box-shadow:0_16px_45px_rgba(31,_43,_38,_0.12)] lg:[transform:translateX(-50%)]',
    'order-detail-products':
        '[margin-top:9px] [padding:0_14px] [background:white] [&>header]:[min-height:46px] [&>header]:[border-bottom:1px_solid_var(--line)] [&>header]:[display:flex] [&>header]:[align-items:center] [&>header]:[justify-content:space-between] [&>header_strong]:[font-weight:var(--font-weight-semibold)] [&>header_span]:[color:var(--muted)] [&_article]:[min-height:92px] [&_article]:[padding:10px_0] [&_article]:[border-bottom:1px_solid_var(--line)] [&_article]:[display:grid] [&_article]:[grid-template-columns:72px_minmax(0,_1fr)_auto] [&_article]:[align-items:start] [&_article]:[gap:9px] [&_article:last-child]:[border-bottom:0] [&_article>img]:[width:72px] [&_article>img]:[height:72px] [&_article>img]:[border-radius:7px] [&_article>img]:[background:var(--product-media-bg)] [&_article>img]:[object-fit:contain] [&_article>.responsive-picture>img]:[width:72px] [&_article>.responsive-picture>img]:[height:72px] [&_article>.responsive-picture>img]:[border-radius:7px] [&_article>.responsive-picture>img]:[background:var(--product-media-bg)] [&_article>.responsive-picture>img]:[object-fit:contain] [&_article>.image-placeholder]:[width:72px] [&_article>.image-placeholder]:[height:72px] [&_article>.image-placeholder]:[border-radius:7px] [&_article>.image-placeholder]:[background:var(--product-media-bg)] [&_article>.image-placeholder]:[object-fit:contain] [&_article>div_strong]:[display:block] [&_article>div_small]:[display:block] [&_article>div_em]:[display:block] [&_article>span_b]:[display:block] [&_article>span_small]:[display:block] [&_article>div_strong]:[overflow:hidden] [&_article>div_strong]:[font-weight:600] [&_article>div_strong]:[white-space:nowrap] [&_article>div_strong]:[text-overflow:ellipsis] [&_article_small]:[margin-top:4px] [&_article_small]:[color:var(--muted)] [&_article_em]:[margin-top:6px] [&_article_em]:[color:var(--success)] [&_article_em]:[font-size:13px] [&_article_em]:[font-style:normal] [&_article>span]:[text-align:right] lg:[width:100%] lg:[max-width:none] lg:[margin-right:auto] lg:[margin-left:auto] lg:[margin-top:20px] lg:[border:1px_solid_var(--line)] lg:[border-radius:8px]',
    'order-detail-summary':
        '[margin-top:9px] [padding:0_14px] [background:white] [padding:11px_14px] lg:[width:100%] lg:[max-width:none] lg:[margin-right:auto] lg:[margin-left:auto] lg:[margin-top:20px] lg:[border:1px_solid_var(--line)] lg:[border-radius:8px]',
    'order-information':
        '[margin-top:9px] [padding:0_14px] [background:white] [padding:7px_14px] [&>div]:[min-height:40px] [&>div]:[display:flex] [&>div]:[align-items:center] [&>div]:[justify-content:space-between] [&>div]:[gap:12px] [&_span]:[color:var(--muted)] [&_b]:[overflow:hidden] [&_b]:[font-weight:500] [&_b]:[white-space:nowrap] [&_b]:[text-overflow:ellipsis] lg:[width:100%] lg:[max-width:none] lg:[margin-right:auto] lg:[margin-left:auto] lg:[margin-top:20px] lg:[border:1px_solid_var(--line)] lg:[border-radius:8px]',
    'order-list':
        '[padding:12px_12px_32px] [display:flex] [flex-direction:column] [gap:12px] lg:[width:100%] lg:[max-width:none] lg:[margin-right:auto] lg:[margin-left:auto] lg:[padding-top:24px] lg:[display:grid] lg:[grid-template-columns:repeat(2,_minmax(0,_1fr))] lg:[gap:20px]',
    'order-load-more': '[width:100%] [margin-top:4px]',
    'order-logistics':
        '[min-height:68px] [margin-top:9px] [padding:10px_14px] [background:white] [display:grid] [grid-template-columns:28px_minmax(0,_1fr)] [align-items:center] [gap:9px] [&>svg:first-child]:[color:var(--success)] [&_strong]:[display:block] [&_small]:[display:block] [&_small]:[margin-top:4px] [&_small]:[color:var(--muted)] lg:[width:100%] lg:[max-width:none] lg:[margin-right:auto] lg:[margin-left:auto] lg:[margin-top:20px] lg:[border:1px_solid_var(--line)] lg:[border-radius:8px]',
    'order-logistics-content': '[min-width:0]',
    'order-logistics-item':
        '[margin-top:9px] [padding-top:9px] [border-top:1px_solid_var(--line)] [display:grid] [grid-template-columns:minmax(0,_1fr)_auto] [gap:3px_10px] [&_span]:[min-width:0] [&_span]:[overflow-wrap:anywhere] [&_b]:[min-width:0] [&_b]:[overflow-wrap:anywhere] [&_em]:[min-width:0] [&_em]:[overflow-wrap:anywhere] [&_span]:[font-style:normal] [&_span]:[font-weight:600] [&_b]:[font-style:normal] [&_b]:[font-weight:600] [&_small]:[margin:0] [&_small]:[text-align:right] [&_b]:[grid-column:1_/_-1] [&_em]:[grid-column:1_/_-1] [&_em]:[color:var(--muted)] [&_em]:[font-size:13px] [&_em]:[font-style:normal]',
    'order-product-info': '[min-width:0] [display:flex] [flex-direction:column] [gap:4px]',
    'order-product-meta':
        '[text-align:right] [display:flex] [flex-direction:column] [align-items:flex-end] [gap:3px] [flex-shrink:0]',
    'order-product-price':
        '[font-size:14px] [font-weight:var(--font-weight-bold)] [color:var(--text)] [white-space:nowrap]',
    'order-product-qty': '[font-size:12px] [color:var(--muted)]',
    'order-product-spec':
        '[font-size:12px] [color:var(--muted)] [overflow:hidden] [white-space:nowrap] [text-overflow:ellipsis]',
    'order-product-tag':
        '[padding:1px_6px] [border-radius:4px] [background:#f0fdf4] [color:#16a34a] [font-size:10px] [font-weight:500] [border:1px_solid_rgba(22,_163,_74,_0.2)]',
    'order-product-tags': '[display:flex] [align-items:center] [gap:6px] [margin-top:2px]',
    'order-product-title':
        '[font-size:14px] [font-weight:var(--font-weight-semibold)] [color:var(--text)] [line-height:1.4] [overflow:hidden] [display:-webkit-box] [-webkit-box-orient:vertical] [-webkit-line-clamp:2]',
    'order-search':
        "[min-height:52px] [padding:7px_10px] [border-bottom:1px_solid_var(--line)] [background:white] [display:grid] [grid-template-columns:18px_minmax(0,_1fr)_auto_auto] [align-items:center] [gap:7px] [&>svg]:[width:18px] [&>svg]:[color:var(--muted)] [&_input]:[min-width:0] [&_input]:[height:38px] [&_input]:[padding:0] [&_input]:[border:0] [&_input]:[outline:0] [&_input]:[background:transparent] [&_button]:[min-width:38px] [&_button]:[height:38px] [&_button]:[padding:0_9px] [&_button]:[border:0] [&_button]:[border-radius:6px] [&_button]:[background:transparent] [&_button]:[color:var(--muted)] [&_button[type='submit']]:[background:var(--accent)] [&_button[type='submit']]:[color:white] [&_button_svg]:[width:17px]",
    'order-status':
        '[padding:22px_14px_19px] [background:var(--accent-soft)] [color:#8e3b34] [&_strong]:[display:block] [&_span]:[display:block] [&_small]:[display:block] [&_strong]:[font-size:20px] [&_strong]:[font-weight:var(--font-weight-semibold)] [&_span]:[margin-top:5px] [&_small]:[margin-top:8px] [&_small]:[color:#a56660] lg:[width:100%] lg:[max-width:none] lg:[margin-right:auto] lg:[margin-left:auto] lg:[margin-top:24px] lg:[border-radius:8px]',
    'order-tabs':
        '[height:46px] [padding:0_8px] [position:sticky] [z-index:9] [top:52px] [border-bottom:1px_solid_rgba(226,_232,_240,_0.85)] [background:rgba(255,_255,_255,_0.96)] [backdrop-filter:blur(12px)] [display:grid] [grid-template-columns:repeat(5,_minmax(0,_1fr))] [&_button]:[min-width:0] [&_button]:[padding:0_2px] [&_button]:[border:0] [&_button]:[border-bottom:2.5px_solid_transparent] [&_button]:[background:transparent] [&_button]:[color:var(--muted)] [&_button]:[font-size:clamp(10.5px,_3.35vw,_14px)] [&_button]:[font-weight:500] [&_button]:[letter-spacing:-0.01em] [&_button]:[white-space:nowrap] [&_button]:[cursor:pointer] [&_button]:[transition:all_160ms_ease] [&_button:hover]:[color:var(--text)] [&_button.is-active]:[border-bottom-color:var(--accent)] [&_button.is-active]:[color:var(--accent)] [&_button.is-active]:[font-weight:var(--font-weight-bold)] lg:[height:56px] lg:[top:72px]',
    'order-total-amount': '[font-size:15px] [font-weight:800] [color:#0f172a]',
    'order-total-count': '[color:#64748b] [font-size:12px]',
    'order-total-label': '[color:#334155] [font-size:12px] [font-weight:500]',
    'order-total-summary':
        '[&_b]:[font-family:var(--font-numeric)] [&_b]:[font-variant-numeric:tabular-nums] [&_b]:[letter-spacing:-0.02em] [display:flex] [align-items:baseline] [gap:4px] [font-size:12px] [color:var(--muted)] [min-width:0] [flex-wrap:wrap]',
    'orders-page':
        '[--page-surface:var(--paper)] lg:[&>.empty-state]:[width:100%] lg:[&>.empty-state]:[max-width:none] lg:[&>.empty-state]:[margin:24px_auto_0]',
    'service-strip-item':
        '[display:flex] [align-items:center] [gap:4px] [font-size:11px] [font-weight:600] [color:#64748b] [&_svg]:[color:#0284c7]',
    'stat-card-count':
        '[font-size:15px] [font-weight:800] [color:#0f172a] [font-family:var(--font-numeric)] [.logistics-stat-card.is-active_&]:[color:#d33c30]',
    'stat-card-icon':
        '[width:28px] [height:28px] [border-radius:8px] [display:grid] [place-items:center] [flex-shrink:0] [&.icon-all]:[background:#f1f5f9] [&.icon-all]:[color:#475569] [&.icon-transit]:[background:#eff6ff] [&.icon-transit]:[color:#2563eb] [&.icon-preparing]:[background:#fff7ed] [&.icon-preparing]:[color:#ea580c] [&.icon-delivered]:[background:#ecfdf5] [&.icon-delivered]:[color:#059669]',
    'stat-card-label':
        '[font-size:11px] [font-weight:700] [color:#64748b] [white-space:nowrap] [overflow:hidden] [text-overflow:ellipsis] [.logistics-stat-card.is-active_&]:[color:#0f172a] [.logistics-stat-card.is-active_&]:[font-weight:800]',
    'stat-card-top':
        '[width:100%] [display:flex] [align-items:center] [justify-content:space-between] [padding:0_2px]',
};
