export {
    AUTHENTICATED_ROUTE_PREFIX,
    CUSTOMER_ROLE_CODE,
    CurrencyCode,
    DEFAULT_CHANNEL_CODE,
    LS_KEY_SELECTED_CHANNEL_TOKEN,
    LS_KEY_SESSION_TOKEN,
    LS_KEY_SHIPPING_TEST_ADDRESS,
    LS_KEY_SHIPPING_TEST_ORDER,
    LS_KEY_USER_SETTINGS,
    NEW_ENTITY_PATH,
    SUPER_ADMIN_ROLE_CODE,
} from '@/vdb/constants.js';
