/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AccountSecurityRouteImport } from './routes/account-security'
import { Route as AddressesRouteImport } from './routes/addresses'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CategoryRouteImport } from './routes/category'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CouponsRouteImport } from './routes/coupons'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as FlashSaleRouteImport } from './routes/flash-sale'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ImageStudioRouteImport } from './routes/image-studio'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogisticsRouteImport } from './routes/logistics'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OrderConfirmationRouteImport } from './routes/order-confirmation'
import { Route as OrderDetailRouteImport } from './routes/order-detail'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as ProductRouteImport } from './routes/product'
import { Route as PurchaseRouteImport } from './routes/purchase'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as ReferralRouteImport } from './routes/referral'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TwoFactorRouteImport } from './routes/two-factor'
import { Route as VerifyAccountRouteImport } from './routes/verify-account'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: '/account-security',
  path: '/account-security',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressesRoute = AddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryRoute = CategoryRouteImport.update({
  id: '/category',
  path: '/category',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponsRoute = CouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashSaleRoute = FlashSaleRouteImport.update({
  id: '/flash-sale',
  path: '/flash-sale',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageStudioRoute = ImageStudioRouteImport.update({
  id: '/image-studio',
  path: '/image-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsRoute = LogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationRoute = OrderConfirmationRouteImport.update({
  id: '/order-confirmation',
  path: '/order-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderDetailRoute = OrderDetailRouteImport.update({
  id: '/order-detail',
  path: '/order-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRoute = PurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralRoute = ReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TwoFactorRoute = TwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyAccountRoute = VerifyAccountRouteImport.update({
  id: '/verify-account',
  path: '/verify-account',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/account-security': typeof AccountSecurityRoute
  '/addresses': typeof AddressesRoute
  '/announcements': typeof AnnouncementsRoute
  '/cart': typeof CartRoute
  '/category': typeof CategoryRoute
  '/checkout': typeof CheckoutRoute
  '/coupons': typeof CouponsRoute
  '/favorites': typeof FavoritesRoute
  '/flash-sale': typeof FlashSaleRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/image-studio': typeof ImageStudioRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/logistics': typeof LogisticsRoute
  '/not-found': typeof NotFoundRoute
  '/notifications': typeof NotificationsRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/order-detail': typeof OrderDetailRoute
  '/orders': typeof OrdersRoute
  '/payment': typeof PaymentRoute
  '/product': typeof ProductRoute
  '/purchase': typeof PurchaseRoute
  '/recommendations': typeof RecommendationsRoute
  '/referral': typeof ReferralRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/support': typeof SupportRoute
  '/two-factor': typeof TwoFactorRoute
  '/verify-account': typeof VerifyAccountRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/account-security': typeof AccountSecurityRoute
  '/addresses': typeof AddressesRoute
  '/announcements': typeof AnnouncementsRoute
  '/cart': typeof CartRoute
  '/category': typeof CategoryRoute
  '/checkout': typeof CheckoutRoute
  '/coupons': typeof CouponsRoute
  '/favorites': typeof FavoritesRoute
  '/flash-sale': typeof FlashSaleRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/image-studio': typeof ImageStudioRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/logistics': typeof LogisticsRoute
  '/not-found': typeof NotFoundRoute
  '/notifications': typeof NotificationsRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/order-detail': typeof OrderDetailRoute
  '/orders': typeof OrdersRoute
  '/payment': typeof PaymentRoute
  '/product': typeof ProductRoute
  '/purchase': typeof PurchaseRoute
  '/recommendations': typeof RecommendationsRoute
  '/referral': typeof ReferralRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/support': typeof SupportRoute
  '/two-factor': typeof TwoFactorRoute
  '/verify-account': typeof VerifyAccountRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/account-security': typeof AccountSecurityRoute
  '/addresses': typeof AddressesRoute
  '/announcements': typeof AnnouncementsRoute
  '/cart': typeof CartRoute
  '/category': typeof CategoryRoute
  '/checkout': typeof CheckoutRoute
  '/coupons': typeof CouponsRoute
  '/favorites': typeof FavoritesRoute
  '/flash-sale': typeof FlashSaleRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/image-studio': typeof ImageStudioRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/logistics': typeof LogisticsRoute
  '/not-found': typeof NotFoundRoute
  '/notifications': typeof NotificationsRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/order-detail': typeof OrderDetailRoute
  '/orders': typeof OrdersRoute
  '/payment': typeof PaymentRoute
  '/product': typeof ProductRoute
  '/purchase': typeof PurchaseRoute
  '/recommendations': typeof RecommendationsRoute
  '/referral': typeof ReferralRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/support': typeof SupportRoute
  '/two-factor': typeof TwoFactorRoute
  '/verify-account': typeof VerifyAccountRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/account-security'
    | '/addresses'
    | '/announcements'
    | '/cart'
    | '/category'
    | '/checkout'
    | '/coupons'
    | '/favorites'
    | '/flash-sale'
    | '/forgot-password'
    | '/history'
    | '/home'
    | '/image-studio'
    | '/legal'
    | '/login'
    | '/logistics'
    | '/not-found'
    | '/notifications'
    | '/order-confirmation'
    | '/order-detail'
    | '/orders'
    | '/payment'
    | '/product'
    | '/purchase'
    | '/recommendations'
    | '/referral'
    | '/register'
    | '/reset-password'
    | '/reviews'
    | '/search'
    | '/services'
    | '/support'
    | '/two-factor'
    | '/verify-account'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/account-security'
    | '/addresses'
    | '/announcements'
    | '/cart'
    | '/category'
    | '/checkout'
    | '/coupons'
    | '/favorites'
    | '/flash-sale'
    | '/forgot-password'
    | '/history'
    | '/home'
    | '/image-studio'
    | '/legal'
    | '/login'
    | '/logistics'
    | '/not-found'
    | '/notifications'
    | '/order-confirmation'
    | '/order-detail'
    | '/orders'
    | '/payment'
    | '/product'
    | '/purchase'
    | '/recommendations'
    | '/referral'
    | '/register'
    | '/reset-password'
    | '/reviews'
    | '/search'
    | '/services'
    | '/support'
    | '/two-factor'
    | '/verify-account'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/account-security'
    | '/addresses'
    | '/announcements'
    | '/cart'
    | '/category'
    | '/checkout'
    | '/coupons'
    | '/favorites'
    | '/flash-sale'
    | '/forgot-password'
    | '/history'
    | '/home'
    | '/image-studio'
    | '/legal'
    | '/login'
    | '/logistics'
    | '/not-found'
    | '/notifications'
    | '/order-confirmation'
    | '/order-detail'
    | '/orders'
    | '/payment'
    | '/product'
    | '/purchase'
    | '/recommendations'
    | '/referral'
    | '/register'
    | '/reset-password'
    | '/reviews'
    | '/search'
    | '/services'
    | '/support'
    | '/two-factor'
    | '/verify-account'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AccountSecurityRoute: typeof AccountSecurityRoute
  AddressesRoute: typeof AddressesRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  CartRoute: typeof CartRoute
  CategoryRoute: typeof CategoryRoute
  CheckoutRoute: typeof CheckoutRoute
  CouponsRoute: typeof CouponsRoute
  FavoritesRoute: typeof FavoritesRoute
  FlashSaleRoute: typeof FlashSaleRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HistoryRoute: typeof HistoryRoute
  HomeRoute: typeof HomeRoute
  ImageStudioRoute: typeof ImageStudioRoute
  LegalRoute: typeof LegalRoute
  LoginRoute: typeof LoginRoute
  LogisticsRoute: typeof LogisticsRoute
  NotFoundRoute: typeof NotFoundRoute
  NotificationsRoute: typeof NotificationsRoute
  OrderConfirmationRoute: typeof OrderConfirmationRoute
  OrderDetailRoute: typeof OrderDetailRoute
  OrdersRoute: typeof OrdersRoute
  PaymentRoute: typeof PaymentRoute
  ProductRoute: typeof ProductRoute
  PurchaseRoute: typeof PurchaseRoute
  RecommendationsRoute: typeof RecommendationsRoute
  ReferralRoute: typeof ReferralRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReviewsRoute: typeof ReviewsRoute
  SearchRoute: typeof SearchRoute
  ServicesRoute: typeof ServicesRoute
  SupportRoute: typeof SupportRoute
  TwoFactorRoute: typeof TwoFactorRoute
  VerifyAccountRoute: typeof VerifyAccountRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-security': {
      id: '/account-security'
      path: '/account-security'
      fullPath: '/account-security'
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addresses': {
      id: '/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category': {
      id: '/category'
      path: '/category'
      fullPath: '/category'
      preLoaderRoute: typeof CategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupons': {
      id: '/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof CouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flash-sale': {
      id: '/flash-sale'
      path: '/flash-sale'
      fullPath: '/flash-sale'
      preLoaderRoute: typeof FlashSaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-studio': {
      id: '/image-studio'
      path: '/image-studio'
      fullPath: '/image-studio'
      preLoaderRoute: typeof ImageStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics': {
      id: '/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof LogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmation': {
      id: '/order-confirmation'
      path: '/order-confirmation'
      fullPath: '/order-confirmation'
      preLoaderRoute: typeof OrderConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-detail': {
      id: '/order-detail'
      path: '/order-detail'
      fullPath: '/order-detail'
      preLoaderRoute: typeof OrderDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase': {
      id: '/purchase'
      path: '/purchase'
      fullPath: '/purchase'
      preLoaderRoute: typeof PurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral': {
      id: '/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof ReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/two-factor': {
      id: '/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof TwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-account': {
      id: '/verify-account'
      path: '/verify-account'
      fullPath: '/verify-account'
      preLoaderRoute: typeof VerifyAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AccountSecurityRoute: AccountSecurityRoute,
  AddressesRoute: AddressesRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  CartRoute: CartRoute,
  CategoryRoute: CategoryRoute,
  CheckoutRoute: CheckoutRoute,
  CouponsRoute: CouponsRoute,
  FavoritesRoute: FavoritesRoute,
  FlashSaleRoute: FlashSaleRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HistoryRoute: HistoryRoute,
  HomeRoute: HomeRoute,
  ImageStudioRoute: ImageStudioRoute,
  LegalRoute: LegalRoute,
  LoginRoute: LoginRoute,
  LogisticsRoute: LogisticsRoute,
  NotFoundRoute: NotFoundRoute,
  NotificationsRoute: NotificationsRoute,
  OrderConfirmationRoute: OrderConfirmationRoute,
  OrderDetailRoute: OrderDetailRoute,
  OrdersRoute: OrdersRoute,
  PaymentRoute: PaymentRoute,
  ProductRoute: ProductRoute,
  PurchaseRoute: PurchaseRoute,
  RecommendationsRoute: RecommendationsRoute,
  ReferralRoute: ReferralRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReviewsRoute: ReviewsRoute,
  SearchRoute: SearchRoute,
  ServicesRoute: ServicesRoute,
  SupportRoute: SupportRoute,
  TwoFactorRoute: TwoFactorRoute,
  VerifyAccountRoute: VerifyAccountRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
