import { randomBytes } from 'node:crypto';
import { describe, expect, it } from 'vitest';

import {
    AdminTwoFactorCrypto,
    createRecoveryCodes,
    createTotpSecret,
    matchTotpStep,
    totpAtStep,
} from './admin-two-factor.crypto';

describe('administrator TOTP cryptography', () => {
    // Published RFC 6238 SHA-1 vectors, rather than expected values generated by our implementation.
    it.each([
        [59, '94287082'],
        [1111111109, '07081804'],
        [1111111111, '14050471'],
        [1234567890, '89005924'],
        [2000000000, '69279037'],
        [20000000000, '65353130'],
    ])('matches RFC 6238 at %s seconds', (seconds, expected) => {
        expect(totpAtStep('GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ', Math.floor(Number(seconds) / 30), 8)).toBe(
            expected,
        );
    });

    it('accepts limited clock skew but rejects replay, malformed and expired codes', () => {
        const secret = createTotpSecret();
        const step = 123456;
        expect(matchTotpStep(secret, totpAtStep(secret, step), -1, step * 30000)).toBe(step);
        expect(matchTotpStep(secret, totpAtStep(secret, step - 1), -1, step * 30000)).toBe(step - 1);
        expect(matchTotpStep(secret, totpAtStep(secret, step), step, step * 30000)).toBeNull();
        expect(matchTotpStep(secret, totpAtStep(secret, step - 2), -1, step * 30000)).toBeNull();
        expect(matchTotpStep(secret, '12345', -1, step * 30000)).toBeNull();
    });

    it('encrypts with randomized nonces and binds ciphertext to its administrator', () => {
        const crypto = new AdminTwoFactorCrypto(randomBytes(32).toString('hex'));
        const secret = createTotpSecret();
        const encrypted = crypto.encrypt(secret, 'admin-1');
        expect(encrypted).not.toContain(secret);
        expect(crypto.encrypt(secret, 'admin-1')).not.toBe(encrypted);
        expect(crypto.decrypt(encrypted, 'admin-1')).toBe(secret);
        expect(() => crypto.decrypt(encrypted, 'admin-2')).toThrow();
        expect(() => crypto.decrypt(encrypted.slice(0, -4) + 'AAAA', 'admin-1')).toThrow();
        expect(() =>
            new AdminTwoFactorCrypto(randomBytes(32).toString('hex')).decrypt(encrypted, 'admin-1'),
        ).toThrow();
    });

    it('has no fallback key and produces high-entropy single-use recovery material', () => {
        expect(new AdminTwoFactorCrypto('replace-me').available).toBe(false);
        expect(() => new AdminTwoFactorCrypto('').encrypt('secret', '1')).toThrow();
        const codes = createRecoveryCodes();
        expect(new Set(codes).size).toBe(10);
        expect(codes.every(code => /^(?:[A-F0-9]{4}-){7}[A-F0-9]{4}$/.test(code))).toBe(true);
    });
});
