/* This file is generated by image-prompt-pro/scripts/compile.mjs. Do not edit. */
const promptRulesBundle = {
  "bundleVersion": 1,
  "models": [
    {
      "code": "GEMINI_FLASH",
      "displayNameEn": "Gemini Fast",
      "displayNameZh": "Gemini 快速",
      "officialModelId": "gemini-3.1-flash-image",
      "renderer": {
        "preferNaturalLanguage": true,
        "supportsNegativePrompt": false,
        "supportsReferenceImage": true
      },
      "strengths": [
        "general",
        "product-scene",
        "social-art",
        "illustration"
      ]
    },
    {
      "code": "GEMINI_PRO",
      "displayNameEn": "Gemini Pro",
      "displayNameZh": "Gemini 专业",
      "officialModelId": "gemini-3-pro-image",
      "renderer": {
        "preferNaturalLanguage": true,
        "supportsNegativePrompt": false,
        "supportsReferenceImage": true
      },
      "strengths": [
        "exact-text",
        "poster",
        "infographic",
        "complex-layout"
      ]
    },
    {
      "code": "OPENAI_HIGH_QUALITY",
      "displayNameEn": "OpenAI High Quality",
      "displayNameZh": "OpenAI 高质量",
      "officialModelId": "gpt-image-1",
      "renderer": {
        "preferNaturalLanguage": true,
        "supportsNegativePrompt": false,
        "supportsReferenceImage": true
      },
      "strengths": [
        "identity-preservation",
        "high-fidelity-edit",
        "transparent-background",
        "product-cutout"
      ]
    }
  ],
  "routing": {
    "defaultStrategy": "BALANCED",
    "rules": [
      {
        "modelCode": "OPENAI_HIGH_QUALITY",
        "priority": 10,
        "reasonEn": "Best suited to identity consistency, precise edits, and transparent backgrounds",
        "reasonZh": "更适合身份一致性、精细编辑和透明背景",
        "when": [
          "identity-preservation",
          "high-fidelity-edit",
          "transparent-background",
          "product-cutout"
        ]
      },
      {
        "modelCode": "GEMINI_PRO",
        "priority": 20,
        "reasonEn": "Best suited to accurate text, posters, and complex layouts",
        "reasonZh": "更适合准确文字、海报和复杂版式",
        "when": [
          "exact-text",
          "poster",
          "infographic",
          "complex-layout"
        ]
      },
      {
        "modelCode": "GEMINI_FLASH",
        "priority": 30,
        "reasonEn": "Balanced for speed and cost",
        "reasonZh": "生成速度与成本更均衡",
        "when": [
          "general",
          "product-scene",
          "social-art",
          "illustration"
        ]
      }
    ],
    "version": 1
  },
  "schema": {
    "$id": "https://example.invalid/image-prompt-pro/prompt-spec.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": false,
    "properties": {
      "avoid": {
        "items": {
          "maxLength": 160,
          "type": "string"
        },
        "maxItems": 30,
        "type": "array"
      },
      "camera": {
        "default": "",
        "maxLength": 500,
        "type": "string"
      },
      "colors": {
        "items": {
          "maxLength": 80,
          "type": "string"
        },
        "maxItems": 12,
        "type": "array"
      },
      "composition": {
        "maxLength": 800,
        "type": "string"
      },
      "exactText": {
        "items": {
          "maxLength": 300,
          "type": "string"
        },
        "maxItems": 20,
        "type": "array"
      },
      "lighting": {
        "maxLength": 500,
        "type": "string"
      },
      "materials": {
        "items": {
          "maxLength": 120,
          "type": "string"
        },
        "maxItems": 12,
        "type": "array"
      },
      "preserve": {
        "items": {
          "maxLength": 200,
          "type": "string"
        },
        "maxItems": 20,
        "type": "array"
      },
      "referenceMode": {
        "enum": [
          "NONE",
          "STYLE",
          "COMPOSITION",
          "IDENTITY",
          "PRODUCT",
          "EDIT"
        ]
      },
      "scene": {
        "maxLength": 800,
        "type": "string"
      },
      "style": {
        "maxLength": 500,
        "type": "string"
      },
      "subject": {
        "maxLength": 1200,
        "type": "string"
      },
      "useCase": {
        "enum": [
          "product-photo",
          "ecommerce-poster",
          "portrait",
          "interior-design",
          "illustration",
          "reference-edit"
        ]
      }
    },
    "required": [
      "useCase",
      "subject",
      "scene",
      "composition",
      "lighting",
      "style",
      "colors",
      "materials",
      "exactText",
      "preserve",
      "avoid",
      "referenceMode"
    ],
    "title": "ImagePromptSpec",
    "type": "object"
  },
  "sourceHash": "1173e49e57b4de6b8c5582ec956ad340d77091ccc02a8791e24ce9dc0cdd0eb4",
  "useCases": [
    {
      "avoid": [
        "invented price",
        "invented promotion",
        "misspelled exact text",
        "unreadable typography"
      ],
      "code": "ecommerce-poster",
      "defaults": {
        "composition": "clear headline, product focus, offer area and call-to-action hierarchy",
        "lighting": "polished campaign lighting",
        "style": "conversion-focused ecommerce poster"
      },
      "required": [
        "subject"
      ]
    },
    {
      "avoid": [
        "unrequested text",
        "muddy hierarchy",
        "accidental signature",
        "visual clutter"
      ],
      "code": "illustration",
      "defaults": {
        "composition": "readable silhouette and clear visual hierarchy",
        "lighting": "coherent stylized lighting",
        "style": "intentional editorial illustration"
      },
      "required": [
        "subject"
      ]
    },
    {
      "avoid": [
        "impossible geometry",
        "floating furniture",
        "blocked circulation",
        "inconsistent shadows"
      ],
      "code": "interior-design",
      "defaults": {
        "composition": "architecturally coherent wide-angle composition",
        "lighting": "physically plausible daylight and practical lights",
        "style": "high-end photoreal interior visualization"
      },
      "required": [
        "subject",
        "scene"
      ]
    },
    {
      "avoid": [
        "age ambiguity",
        "sexualized pose",
        "identity drift",
        "over-smoothed skin"
      ],
      "code": "portrait",
      "defaults": {
        "composition": "natural portrait framing and anatomically plausible pose",
        "lighting": "soft flattering portrait light",
        "style": "tasteful adult commercial portrait"
      },
      "required": [
        "subject"
      ]
    },
    {
      "avoid": [
        "invented branding",
        "invented certification",
        "incorrect packaging text",
        "warped product geometry"
      ],
      "code": "product-photo",
      "defaults": {
        "composition": "clear product hierarchy with intentional negative space",
        "lighting": "controlled commercial lighting",
        "style": "credible ecommerce photography"
      },
      "required": [
        "subject"
      ]
    },
    {
      "avoid": [
        "unrequested identity change",
        "unrequested logo change",
        "product shape drift",
        "lost fine details"
      ],
      "code": "reference-edit",
      "defaults": {
        "composition": "preserve requested reference structure unless explicitly changed",
        "lighting": "match the requested target scene",
        "style": "high-fidelity controlled edit"
      },
      "required": [
        "subject",
        "preserve"
      ]
    }
  ]
};

export default promptRulesBundle;
