/* This file is generated by image-prompt-pro/scripts/compile.mjs. Do not edit. */
const promptRulesBundle = {
    bundleVersion: 1,
    models: [
        {
            code: 'GEMINI_FLASH',
            displayNameEn: 'Gemini 3.1 Flash Image',
            displayNameZh: 'Gemini 3.1 Flash Image',
            officialModelId: 'gemini-3.1-flash-image',
            renderer: {
                preferNaturalLanguage: true,
                supportsNegativePrompt: false,
                supportsReferenceImage: true,
            },
            strengths: ['general', 'illustration', 'fast-draft', 'cost-sensitive'],
        },
        {
            code: 'OPENAI_HIGH_QUALITY',
            displayNameEn: 'Codex Image 1',
            displayNameZh: 'Codex 图片 1',
            officialModelId: 'gpt-image-1',
            renderer: {
                preferNaturalLanguage: true,
                supportsNegativePrompt: false,
                supportsReferenceImage: true,
            },
            strengths: ['product-scene', 'social-art'],
        },
        {
            code: 'OPENAI_IMAGE_1_5',
            displayNameEn: 'Codex Image 1.5',
            displayNameZh: 'Codex 图片 1.5',
            officialModelId: 'gpt-image-1.5',
            renderer: {
                preferNaturalLanguage: true,
                supportsNegativePrompt: false,
                supportsReferenceImage: true,
            },
            strengths: ['high-fidelity-edit', 'transparent-background', 'product-cutout'],
        },
        {
            code: 'OPENAI_IMAGE_2',
            displayNameEn: 'Codex Image 2',
            displayNameZh: 'Codex 图片 2',
            officialModelId: 'gpt-image-2',
            renderer: {
                preferNaturalLanguage: true,
                supportsNegativePrompt: false,
                supportsReferenceImage: true,
            },
            strengths: ['identity-preservation', 'exact-text', 'poster', 'infographic', 'complex-layout'],
        },
    ],
    routing: {
        defaultStrategy: 'BALANCED',
        rules: [
            {
                modelCode: 'OPENAI_IMAGE_2',
                priority: 10,
                reasonEn:
                    'The premium tier is best suited to identity consistency, exact text, and complex layouts',
                reasonZh: '旗舰档更适合身份一致性、准确文字和复杂版式',
                when: ['identity-preservation', 'exact-text', 'poster', 'infographic', 'complex-layout'],
            },
            {
                modelCode: 'OPENAI_IMAGE_1_5',
                priority: 20,
                reasonEn:
                    'The enhanced tier is best suited to precise edits, product cutouts, and transparent backgrounds',
                reasonZh: '增强档更适合精细编辑、商品抠图和透明背景',
                when: ['high-fidelity-edit', 'transparent-background', 'product-cutout'],
            },
            {
                modelCode: 'OPENAI_HIGH_QUALITY',
                priority: 30,
                reasonEn: 'The standard tier is suitable for everyday product scenes and social visuals',
                reasonZh: '标准档适合日常商品场景和社交配图',
                when: ['product-scene', 'social-art'],
            },
            {
                modelCode: 'GEMINI_FLASH',
                priority: 40,
                reasonEn: 'Balanced for fast drafts, speed, and cost',
                reasonZh: '适合快速试稿，生成速度与成本更均衡',
                when: ['general', 'illustration'],
            },
        ],
        version: 1,
    },
    schema: {
        $id: 'https://example.invalid/image-prompt-pro/prompt-spec.schema.json',
        $schema: 'https://json-schema.org/draft/2020-12/schema',
        additionalProperties: false,
        properties: {
            avoid: {
                items: {
                    maxLength: 160,
                    type: 'string',
                },
                maxItems: 30,
                type: 'array',
            },
            camera: {
                default: '',
                maxLength: 500,
                type: 'string',
            },
            colors: {
                items: {
                    maxLength: 80,
                    type: 'string',
                },
                maxItems: 12,
                type: 'array',
            },
            composition: {
                maxLength: 800,
                type: 'string',
            },
            exactText: {
                items: {
                    maxLength: 300,
                    type: 'string',
                },
                maxItems: 20,
                type: 'array',
            },
            lighting: {
                maxLength: 500,
                type: 'string',
            },
            materials: {
                items: {
                    maxLength: 120,
                    type: 'string',
                },
                maxItems: 12,
                type: 'array',
            },
            preserve: {
                items: {
                    maxLength: 200,
                    type: 'string',
                },
                maxItems: 20,
                type: 'array',
            },
            referenceMode: {
                enum: ['NONE', 'STYLE', 'COMPOSITION', 'IDENTITY', 'PRODUCT', 'EDIT'],
            },
            scene: {
                maxLength: 800,
                type: 'string',
            },
            style: {
                maxLength: 500,
                type: 'string',
            },
            subject: {
                maxLength: 1200,
                type: 'string',
            },
            useCase: {
                enum: [
                    'product-photo',
                    'ecommerce-poster',
                    'portrait',
                    'interior-design',
                    'illustration',
                    'reference-edit',
                ],
            },
        },
        required: [
            'useCase',
            'subject',
            'scene',
            'composition',
            'lighting',
            'style',
            'colors',
            'materials',
            'exactText',
            'preserve',
            'avoid',
            'referenceMode',
        ],
        title: 'ImagePromptSpec',
        type: 'object',
    },
    sourceHash: '82e12d43adf47d85990601b4447dfca7a37326dc87cff98950e637bac63a6d47',
    useCases: [
        {
            avoid: ['invented price', 'invented promotion', 'misspelled exact text', 'unreadable typography'],
            code: 'ecommerce-poster',
            defaults: {
                composition: 'clear headline, product focus, offer area and call-to-action hierarchy',
                lighting: 'polished campaign lighting',
                style: 'conversion-focused ecommerce poster',
            },
            required: ['subject'],
        },
        {
            avoid: ['unrequested text', 'muddy hierarchy', 'accidental signature', 'visual clutter'],
            code: 'illustration',
            defaults: {
                composition: 'readable silhouette and clear visual hierarchy',
                lighting: 'coherent stylized lighting',
                style: 'intentional editorial illustration',
            },
            required: ['subject'],
        },
        {
            avoid: [
                'impossible geometry',
                'floating furniture',
                'blocked circulation',
                'inconsistent shadows',
            ],
            code: 'interior-design',
            defaults: {
                composition: 'architecturally coherent wide-angle composition',
                lighting: 'physically plausible daylight and practical lights',
                style: 'high-end photoreal interior visualization',
            },
            required: ['subject', 'scene'],
        },
        {
            avoid: ['age ambiguity', 'sexualized pose', 'identity drift', 'over-smoothed skin'],
            code: 'portrait',
            defaults: {
                composition: 'natural portrait framing and anatomically plausible pose',
                lighting: 'soft flattering portrait light',
                style: 'tasteful adult commercial portrait',
            },
            required: ['subject'],
        },
        {
            avoid: [
                'invented branding',
                'invented certification',
                'incorrect packaging text',
                'warped product geometry',
            ],
            code: 'product-photo',
            defaults: {
                composition: 'clear product hierarchy with intentional negative space',
                lighting: 'controlled commercial lighting',
                style: 'credible ecommerce photography',
            },
            required: ['subject'],
        },
        {
            avoid: [
                'unrequested identity change',
                'unrequested logo change',
                'product shape drift',
                'lost fine details',
            ],
            code: 'reference-edit',
            defaults: {
                composition: 'preserve requested reference structure unless explicitly changed',
                lighting: 'match the requested target scene',
                style: 'high-fidelity controlled edit',
            },
            required: ['subject', 'preserve'],
        },
    ],
};

export default promptRulesBundle;
