import { createHash } from 'node:crypto';
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const skillRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const referencesRoot = path.join(skillRoot, 'references');
const outputPath = path.join(skillRoot, 'dist', 'prompt-rules.bundle.json');
const runtimeOutputPath = path.join(skillRoot, '..', '..', 'src', 'prompt', 'prompt-rules.bundle.json');
const runtimeModulePath = path.join(skillRoot, '..', '..', 'src', 'prompt', 'prompt-rules.bundle.ts');

const readJson = async filePath => JSON.parse(await readFile(filePath, 'utf8'));
const sortObject = value => {
    if (Array.isArray(value)) return value.map(sortObject);
    if (!value || typeof value !== 'object') return value;
    return Object.fromEntries(
        Object.keys(value)
            .sort()
            .map(key => [key, sortObject(value[key])]),
    );
};

const modelFiles = (await readdir(path.join(referencesRoot, 'model-profiles')))
    .filter(name => name.endsWith('.json'))
    .sort();
const useCaseFiles = (await readdir(path.join(referencesRoot, 'use-cases')))
    .filter(name => name.endsWith('.json'))
    .sort();
const sources = {
    schema: await readJson(path.join(referencesRoot, 'prompt-spec.schema.json')),
    routing: await readJson(path.join(referencesRoot, 'model-routing.json')),
    models: await Promise.all(
        modelFiles.map(name => readJson(path.join(referencesRoot, 'model-profiles', name))),
    ),
    useCases: await Promise.all(
        useCaseFiles.map(name => readJson(path.join(referencesRoot, 'use-cases', name))),
    ),
};

const modelCodes = new Set(sources.models.map(model => model.code));
for (const rule of sources.routing.rules) {
    if (!modelCodes.has(rule.modelCode)) throw new Error(`Unknown routed model: ${rule.modelCode}`);
}
const useCaseCodes = new Set(sources.useCases.map(useCase => useCase.code));
for (const code of sources.schema.properties.useCase.enum) {
    if (!useCaseCodes.has(code)) throw new Error(`Missing use-case profile: ${code}`);
}

const canonicalSources = JSON.stringify(sortObject(sources));
const hash = createHash('sha256').update(canonicalSources).digest('hex');
const bundle = sortObject({ bundleVersion: 1, sourceHash: hash, ...sources });
await mkdir(path.dirname(outputPath), { recursive: true });
const serialized = `${JSON.stringify(bundle, null, 2)}\n`;
const generatedModule = [
    '/* This file is generated by image-prompt-pro/scripts/compile.mjs. Do not edit. */',
    `const promptRulesBundle = ${serialized.trim()};`,
    '',
    'export default promptRulesBundle;',
    '',
].join('\n');
await writeFile(outputPath, serialized, 'utf8');
await mkdir(path.dirname(runtimeOutputPath), { recursive: true });
await writeFile(runtimeOutputPath, serialized, 'utf8');
await writeFile(runtimeModulePath, generatedModule, 'utf8');
process.stdout.write(`${outputPath}\n${hash}\n`);
