name: Lint PR title

on:
    pull_request:
        types: [opened, edited, reopened, synchronize]

permissions:
    contents: read

jobs:
    lint-pr-title:
        name: conventional commit format
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
            - uses: ./.github/actions/setup
            - name: Lint pull request title
              env:
                  PR_TITLE: ${{ github.event.pull_request.title }}
              run: printf '%s\n' "$PR_TITLE" | bunx commitlint
