import { cancel, isCancel, spinner } from '@clack/prompts';
import spawn from 'cross-spawn';
import fs from 'fs-extra';
import Handlebars from 'handlebars';
import { execFile, execFileSync, execSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { createWriteStream } from 'node:fs';
import { Socket } from 'node:net';
import { platform } from 'node:os';
import path from 'node:path';
import { Readable } from 'node:stream';
import { pipeline } from 'node:stream/promises';
import { promisify } from 'node:util';
import pc from 'picocolors';
import semver from 'semver';
import * as tar from 'tar';

import {
    CONCURRENTLY_VERSION,
    DEFAULT_PROJECT_VERSION,
    OLDEST_NON_EOL_NODE_MAJOR,
    PG_READY_MAX_ATTEMPTS,
    PG_READY_POLL_INTERVAL_MS,
    SOCKET_TIMEOUT_MS,
    STOREFRONT_BRANCH,
    STOREFRONT_REPO,
    TYPESCRIPT_VERSION,
    VITE_VERSION,
} from './constants';
import { log } from './logger';
import { CliLogLevel, DbType, PackageManager } from './types';

/**
 * If project only contains files generated by GH, it’s safe.
 * Also, if project contains remnant error logs from a previous
 * installation, lets remove them now.
 * We also special case IJ-based products .idea because it integrates with CRA:
 * https://github.com/facebook/create-react-app/pull/368#issuecomment-243446094
 */
export function isSafeToCreateProjectIn(root: string, name: string) {
    // These files should be allowed to remain on a failed install,
    // but then silently removed during the next create.
    const errorLogFilePatterns = ['npm-debug.log', 'yarn-error.log', 'yarn-debug.log'];
    const validFiles = [
        '.DS_Store',
        'Thumbs.db',
        '.git',
        '.gitignore',
        '.idea',
        'README.md',
        'AGENTS.md',
        'LICENSE',
        '.hg',
        '.hgignore',
        '.hgcheck',
        '.npmignore',
        'mkdocs.yml',
        'docs',
        '.travis.yml',
        '.gitlab-ci.yml',
        '.gitattributes',
        'migration.ts',
        'node_modules',
        'package.json',
        'package-lock.json',
        'src',
        'static',
        'tsconfig.json',
        'yarn.lock',
    ];

    const conflicts = fs
        .readdirSync(root)
        .filter(file => !validFiles.includes(file))
        // IntelliJ IDEA creates module files before CRA is launched
        .filter(file => !/\.iml$/.test(file))
        // Don't treat log files from previous installation as conflicts
        .filter(file => !errorLogFilePatterns.some(pattern => file.indexOf(pattern) === 0));

    if (conflicts.length > 0) {
        log(`The directory ${pc.green(name)} contains files that could conflict:`, { newline: 'after' });
        for (const file of conflicts) {
            log(`  ${file}`);
        }
        log('Either try using a new directory name, or remove the files listed above.', {
            newline: 'before',
        });

        return false;
    }

    // Remove any remnant files from a previous installation
    const currentFiles = fs.readdirSync(path.join(root));
    currentFiles.forEach(file => {
        errorLogFilePatterns.forEach(errorLogFilePattern => {
            // This will catch `(npm-debug|yarn-error|yarn-debug).log*` files
            if (file.indexOf(errorLogFilePattern) === 0) {
                fs.removeSync(path.join(root, file));
            }
        });
    });
    return true;
}

export function scaffoldAlreadyExists(root: string, name: string): boolean {
    const scaffoldFiles = ['migration.ts', 'package.json', 'tsconfig.json', 'README.md'];
    const files = fs.readdirSync(root);
    return scaffoldFiles.every(scaffoldFile => files.includes(scaffoldFile));
}

export function checkNodeVersion(requiredVersion: string, currentVersion: string = process.version) {
    if (!semver.satisfies(currentVersion, requiredVersion)) {
        log(
            pc.red(
                `You are running Node ${currentVersion}.` +
                    `Vendure requires Node ${requiredVersion} or higher.` +
                    'Please update your version of Node.',
            ),
        );
        process.exit(1);
    }
    if (semver.major(currentVersion) < OLDEST_NON_EOL_NODE_MAJOR) {
        log(
            pc.yellow(
                `You are running Node ${currentVersion}, which has reached end-of-life. ` +
                    'Native dependencies may no longer provide prebuilt binaries for it, ' +
                    'which can cause installation failures. Consider upgrading to the ' +
                    'current LTS release: https://nodejs.org/en/download',
            ),
        );
    }
}

export function checkThatNpmCanReadCwd() {
    const cwd = process.cwd();
    let childOutput = null;
    try {
        // Note: intentionally using spawn over exec since
        // the problem doesn't reproduce otherwise.
        // `npm config list` is the only reliable way I could find
        // to reproduce the wrong path. Just printing process.cwd()
        // in a Node process was not enough.
        childOutput = spawn.sync('npm', ['config', 'list']).output.join('');
    } catch (err: any) {
        // Something went wrong spawning node.
        // Not great, but it means we can't do this check.
        // We might fail later on, but let's continue.
        return true;
    }
    if (typeof childOutput !== 'string') {
        return true;
    }
    const lines = childOutput.split('\n');
    // `npm config list` output includes the following line:
    // "; cwd = C:\path\to\current\dir" (unquoted)
    // I couldn't find an easier way to get it.
    const prefix = '; cwd = ';
    const line = lines.find(l => l.indexOf(prefix) === 0);
    if (typeof line !== 'string') {
        // Fail gracefully. They could remove it.
        return true;
    }
    const npmCWD = line.substring(prefix.length);
    if (npmCWD === cwd) {
        return true;
    }
    log(
        pc.red(
            'Could not start an npm process in the right directory.\n\n' +
                `The current directory is: ${pc.bold(cwd)}\n` +
                `However, a newly started npm process runs in: ${pc.bold(npmCWD)}\n\n` +
                'This is probably caused by a misconfigured system terminal shell.',
        ),
    );
    if (process.platform === 'win32') {
        log(
            pc.red('On Windows, this can usually be fixed by running:\n\n') +
                `  ${pc.cyan('reg')} delete "HKCU\\Software\\Microsoft\\Command Processor" /v AutoRun /f\n` +
                `  ${pc.cyan(
                    'reg',
                )} delete "HKLM\\Software\\Microsoft\\Command Processor" /v AutoRun /f\n\n` +
                pc.red('Try to run the above two lines in the terminal.\n') +
                pc.red(
                    'To learn more about this problem, read: https://blogs.msdn.microsoft.com/oldnewthing/20071121-00/?p=24433/',
                ),
        );
    }
    return false;
}

/**
 * Detects the package manager used to invoke this CLI from the
 * `npm_config_user_agent` env var that npm/yarn/pnpm/bun all set when running a
 * package's bin. Falls back to npm. This is what lets `bunx @vendure/create`
 * (and the pnpm/yarn equivalents) install with a package manager that is
 * actually on the PATH, rather than hard-failing on a missing `npm` (issue #4390).
 */
export function detectPackageManager(
    userAgent: string | undefined = process.env.npm_config_user_agent,
): PackageManager {
    const name = userAgent?.split(' ')[0]?.split('/')[0];
    if (name === 'yarn' || name === 'pnpm' || name === 'bun') {
        return name;
    }
    return 'npm';
}

/**
 * Builds the package-manager-specific command and args for installing the given
 * dependencies (exact versions, optionally as devDependencies).
 */
export function getInstallCommand(
    packageManager: PackageManager,
    options: { dependencies: string[]; isDevDependencies?: boolean; logLevel: CliLogLevel },
): { command: string; args: string[] } {
    const { dependencies, isDevDependencies = false, logLevel } = options;
    // With no explicit packages, the intent is "install everything declared in the
    // manifest" (e.g. the downloaded storefront). `npm install` does this with no args,
    // but `<pm> add` with no args is an error for yarn/pnpm/bun — so use the plain
    // `install` subcommand, which all four managers accept.
    if (dependencies.length === 0) {
        return { command: packageManager, args: ['install'] };
    }
    switch (packageManager) {
        case 'yarn':
            return {
                command: 'yarn',
                args: ['add', '--exact', ...(isDevDependencies ? ['--dev'] : []), ...dependencies],
            };
        case 'pnpm':
            return {
                command: 'pnpm',
                args: ['add', '--save-exact', ...(isDevDependencies ? ['--save-dev'] : []), ...dependencies],
            };
        case 'bun':
            return {
                command: 'bun',
                args: ['add', '--exact', ...(isDevDependencies ? ['--dev'] : []), ...dependencies],
            };
        default:
            return {
                command: 'npm',
                args: [
                    'install',
                    '--save',
                    '--save-exact',
                    '--loglevel',
                    'error',
                    ...(isDevDependencies ? ['--save-dev'] : []),
                    ...(logLevel === 'verbose' ? ['--verbose'] : []),
                    ...dependencies,
                ],
            };
    }
}

/**
 * Manager-specific command fragments used to generate package.json scripts, CLI
 * instructions, Dockerfiles and READMEs that match the package manager the project
 * was created with. This is the single source of truth for everything that used to
 * be hard-coded as `npm`.
 */
export interface PackageManagerInfo {
    /** The package manager binary, e.g. `npm` | `yarn` | `pnpm` | `bun`. */
    name: PackageManager;
    /** Prefix to run a package.json script, e.g. `npm run` / `pnpm run` / `bun run`. */
    runScript: string;
    /** Prefix to execute a locally-installed bin, e.g. `npx` / `bunx` / `pnpm exec`. */
    exec: string;
    /** Install all deps declared in the manifest, e.g. `npm install` / `pnpm install`. */
    install: string;
    /** Reproducible, lockfile-frozen install for CI & Docker (includes devDependencies). */
    ciInstall: string;
    /** The lockfile this manager writes. */
    lockfile: string;
    /**
     * Whether the manager reads the package.json `workspaces` field (npm/yarn/bun) or
     * requires a `pnpm-workspace.yaml` (pnpm).
     */
    usesPackageJsonWorkspaces: boolean;
    /** Build a command to run a script in a named workspace, e.g. `npm run dev -w server`. */
    workspaceScript(workspace: string, script: string): string;
}

export function getPackageManagerInfo(packageManager: PackageManager): PackageManagerInfo {
    switch (packageManager) {
        case 'yarn':
            // `yarn install` works on both Yarn Classic and Berry (and is immutable by
            // default under CI on Berry); `--immutable`/`--frozen-lockfile` differ between
            // the two, so we avoid them. Yarn is best-effort and not covered by CI.
            return {
                name: 'yarn',
                runScript: 'yarn run',
                exec: 'yarn',
                install: 'yarn install',
                ciInstall: 'yarn install',
                lockfile: 'yarn.lock',
                usesPackageJsonWorkspaces: true,
                workspaceScript: (workspace, script) => `yarn workspace ${workspace} ${script}`,
            };
        case 'pnpm':
            return {
                name: 'pnpm',
                runScript: 'pnpm run',
                exec: 'pnpm exec',
                install: 'pnpm install',
                ciInstall: 'pnpm install --frozen-lockfile',
                lockfile: 'pnpm-lock.yaml',
                usesPackageJsonWorkspaces: false,
                workspaceScript: (workspace, script) => `pnpm --filter ${workspace} ${script}`,
            };
        case 'bun':
            return {
                name: 'bun',
                runScript: 'bun run',
                exec: 'bunx',
                install: 'bun install',
                ciInstall: 'bun install --frozen-lockfile',
                lockfile: 'bun.lock',
                usesPackageJsonWorkspaces: true,
                workspaceScript: (workspace, script) => `bun run --filter ${workspace} ${script}`,
            };
        default:
            return {
                name: 'npm',
                runScript: 'npm run',
                exec: 'npx',
                install: 'npm install',
                ciInstall: 'npm ci',
                lockfile: 'package-lock.json',
                usesPackageJsonWorkspaces: true,
                workspaceScript: (workspace, script) => `npm run ${script} -w ${workspace}`,
            };
    }
}

/**
 * Returns the scripts for the server package.json. These delegate to the `vendure`
 * CLI's `dev`/`build`/`start` commands, which are package-manager-agnostic.
 */
export function getServerPackageScripts(): Record<string, string> {
    return {
        'dev:server': 'vendure dev server',
        'dev:worker': 'vendure dev worker',
        'dev:dashboard': 'vendure dev dashboard',
        dev: 'vendure dev all',
        build: 'vendure build all',
        'build:server': 'vendure build server',
        'build:worker': 'vendure build worker',
        'build:dashboard': 'vendure build dashboard',
        'start:server': 'node ./dist/index.js',
        'start:worker': 'node ./dist/index-worker.js',
        start: 'vendure start all',
    };
}

/**
 * Returns the root package.json for the monorepo (`--include-storefront`) layout, with
 * workspace scripts written in the syntax of the detected package manager.
 */
export function getMonorepoRootPackageJson(
    name: string,
    pmInfo: PackageManagerInfo,
    dbType: DbType,
): Record<string, unknown> {
    const ws = (workspace: string, script: string) => pmInfo.workspaceScript(workspace, script);
    const pkg: Record<string, unknown> = {
        name,
        version: '0.1.0',
        private: true,
        scripts: {
            dev: `concurrently -n server,storefront -c blue,magenta "${ws('server', 'dev')}" "${ws('storefront', 'dev')}"`,
            'dev:server': ws('server', 'dev'),
            'dev:storefront': ws('storefront', 'dev'),
            build: `${ws('server', 'build')} && ${ws('storefront', 'build')}`,
            'build:server': ws('server', 'build'),
            'build:storefront': ws('storefront', 'build'),
            start: `concurrently -n server,storefront -c blue,magenta "${ws('server', 'start')}" "${ws('storefront', 'start')}"`,
            'start:server': ws('server', 'start'),
            'start:storefront': ws('storefront', 'start'),
        },
        devDependencies: {
            concurrently: CONCURRENTLY_VERSION,
        },
    };
    if (pmInfo.usesPackageJsonWorkspaces) {
        pkg.workspaces = ['apps/*'];
    }
    if (pmInfo.name === 'yarn') {
        pkg.dependenciesMeta = getYarnDependenciesMeta(dbType);
    }
    return pkg;
}

/**
 * Returns the root package.json for the single-project (non-monorepo) layout.
 */
export function getSingleProjectPackageJson(
    name: string,
    pmInfo: PackageManagerInfo,
    dbType: DbType,
): Record<string, unknown> {
    const pkg: Record<string, unknown> = {
        name,
        version: DEFAULT_PROJECT_VERSION,
        private: true,
        scripts: getServerPackageScripts(),
    };
    if (pmInfo.name === 'yarn') {
        pkg.dependenciesMeta = getYarnDependenciesMeta(dbType);
    }
    return pkg;
}

/**
 * Native dependencies whose install/build scripts must run for the scaffolded project to
 * work — otherwise e.g. better-sqlite3's native binding is never compiled and the server
 * crashes on startup. pnpm (v10+) and yarn (v4.14+) block dependency build scripts unless
 * allowlisted, so this list feeds their respective allowlist mechanisms.
 * `bcrypt` (core), `sharp` (asset-server-plugin) and `esbuild` (vite) are always present;
 * SQLite adds `better-sqlite3`.
 *
 * This list is derived from the scaffold's transitive native deps; re-check it against
 * `getDependencies()` whenever Vendure's direct native-dep surface changes.
 */
export function getNativeBuildDependencies(dbType: DbType): string[] {
    const deps = ['bcrypt', 'esbuild', 'sharp'];
    if (dbType === 'sqlite') {
        deps.push('better-sqlite3');
    }
    return deps.sort((a, b) => a.localeCompare(b));
}

/**
 * Yarn ≥4.14 does not run dependency build scripts unless they are allowlisted via
 * `dependenciesMeta` in the top-level package.json (`built: true` per package).
 */
export function getYarnDependenciesMeta(dbType: DbType): Record<string, { built: true }> {
    return Object.fromEntries(getNativeBuildDependencies(dbType).map(dep => [dep, { built: true }]));
}

/**
 * Generates the pnpm-workspace.yaml contents. Since pnpm v11, this file is the only place
 * pnpm reads its settings from (the package.json `pnpm` field is ignored), and it is also
 * where build-script permissions live: v10 uses `onlyBuiltDependencies`, v11 replaced it
 * with `allowBuilds`. Both keys are written so the scaffold works under either version.
 */
export function getPnpmWorkspaceYaml(dbType: DbType, packagesGlobs?: string[]): string {
    const nativeDeps = getNativeBuildDependencies(dbType);
    const lines: string[] = [];
    if (packagesGlobs?.length) {
        lines.push('packages:');
        for (const glob of packagesGlobs) {
            lines.push(`    - '${glob}'`);
        }
        lines.push('');
    }
    lines.push('# pnpm v10 build-script allowlist');
    lines.push('onlyBuiltDependencies:');
    for (const dep of nativeDeps) {
        lines.push(`    - ${dep}`);
    }
    lines.push('');
    lines.push('# pnpm v11 build-script allowlist');
    lines.push('allowBuilds:');
    for (const dep of nativeDeps) {
        lines.push(`    ${dep}: true`);
    }
    lines.push('');
    lines.push('# pnpm v11 fails the install when a dependency has build scripts not covered by');
    lines.push('# allowBuilds. With this off, uncovered scripts are skipped with a warning instead');
    lines.push('# (as in pnpm v10); the packages concerned work without their build scripts.');
    lines.push('strictDepBuilds: false');
    lines.push('');
    return lines.join('\n');
}

/**
 * Generates the .yarnrc.yml for yarn-created projects. The scaffold (ts-node registration,
 * the `vendure` CLI, the dashboard build) resolves packages from a physical node_modules
 * tree, so Plug'n'Play is disabled.
 */
export function getYarnRcYml(): string {
    return 'nodeLinker: node-modules\n';
}

/**
 * Registers Handlebars helpers that emit package-manager-specific command fragments,
 * so templates (README, Dockerfile, …) render commands matching the manager in use.
 */
export function registerTemplateHelpers(pmInfo: PackageManagerInfo): void {
    Handlebars.registerHelper('pmRunScript', (script: string) => `${pmInfo.runScript} ${script}`);
    Handlebars.registerHelper('pmExec', () => pmInfo.exec);
    Handlebars.registerHelper('pmCiInstall', () => pmInfo.ciInstall);
    Handlebars.registerHelper('pmLockfile', () => pmInfo.lockfile);
}

/**
 * Install packages via the package manager that invoked the CLI.
 * Based on the install function from https://github.com/facebook/create-react-app
 */
export function installPackages(options: {
    dependencies: string[];
    isDevDependencies?: boolean;
    logLevel: CliLogLevel;
    cwd?: string;
    packageManager?: PackageManager;
}): Promise<void> {
    const {
        dependencies,
        isDevDependencies = false,
        logLevel,
        cwd,
        packageManager = detectPackageManager(),
    } = options;
    return new Promise((resolve, reject) => {
        const { command, args } = getInstallCommand(packageManager, {
            dependencies,
            isDevDependencies,
            logLevel,
        });

        // Below verbose, capture output so a failing install can report the actual
        // package-manager error rather than a generic message. Both streams are needed:
        // npm reports errors on stderr, while yarn and pnpm largely report on stdout.
        const child = spawn(command, args, {
            stdio: logLevel === 'verbose' ? 'inherit' : ['ignore', 'pipe', 'pipe'],
            cwd,
        });
        let outputTail = '';
        const collectTail = (chunk: Buffer) => {
            outputTail = (outputTail + chunk.toString()).slice(-4000);
        };
        child.stdout?.on('data', collectTail);
        child.stderr?.on('data', collectTail);
        child.on('error', err => {
            reject(
                new Error(
                    `Could not run \`${command} ${args.join(' ')}\`: ${err.message}. Is ${command} installed and on your PATH?`,
                ),
            );
        });
        child.on('close', code => {
            if (code !== 0) {
                let message = `\`${command} ${args.join(' ')}\` failed with exit code ${String(code)}.`;
                if (outputTail.trim()) {
                    message += `\n\n${outputTail.trim()}`;
                } else if (logLevel !== 'verbose') {
                    message += ' Try running with `--log-level verbose` to diagnose.';
                }
                reject(new Error(message));
                return;
            }
            resolve();
        });
    });
}

export function getDependencies(
    dbType: DbType,
    vendurePkgVersion = '',
): { dependencies: string[]; devDependencies: string[] } {
    const dependencies = [
        `@vendure/core${vendurePkgVersion}`,
        `@vendure/email-plugin${vendurePkgVersion}`,
        `@vendure/asset-server-plugin${vendurePkgVersion}`,
        `@vendure/graphiql-plugin${vendurePkgVersion}`,
        `@vendure/dashboard${vendurePkgVersion}`,
        'dotenv',
        dbDriverPackage(dbType),
    ];
    const devDependencies = [
        `@vendure/cli${vendurePkgVersion}`,
        'ts-node',
        `typescript@${TYPESCRIPT_VERSION}`,
        `vite@${VITE_VERSION}`,
    ];
    return { dependencies, devDependencies };
}

/**
 * Returns the name of the npm driver package for the
 * selected database.
 */
function dbDriverPackage(dbType: DbType): string {
    switch (dbType) {
        case 'mysql':
        case 'mariadb':
            return 'mysql2';
        case 'postgres':
            return 'pg';
        case 'sqlite':
            return 'better-sqlite3';
        default:
            const n: never = dbType;
            log(pc.red(`No driver package configured for type "${dbType as string}"`));
            return '';
    }
}

/**
 * Checks that the specified DB connection options are working (i.e. a connection can be
 * established) and that the named database exists.
 */
export function checkDbConnection(options: any, root: string): Promise<true> {
    switch (options.type) {
        case 'mysql':
            return checkMysqlDbExists(options, root);
        case 'postgres':
            return checkPostgresDbExists(options, root);
        default:
            return Promise.resolve(true);
    }
}

async function checkMysqlDbExists(options: any, root: string): Promise<true> {
    // Use require.resolve to find the package, which handles npm workspace hoisting
    const mysqlPath = require.resolve('mysql2/promise', { paths: [root] });
    const mysql = await import(mysqlPath);
    const connectionOptions = {
        host: options.host,
        user: options.username,
        password: options.password,
        port: options.port,
        database: options.database,
    };

    let connection;
    try {
        // mysql2/promise's createConnection returns a Promise that resolves
        // to a connection once connected, so we must await it.
        connection = await mysql.createConnection(connectionOptions);
    } catch (err: any) {
        if (err.code === 'ER_BAD_DB_ERROR') {
            throwDatabaseDoesNotExist(options.database);
        }
        throwConnectionError(err);
    }

    await connection.end();
    return true;
}

async function checkPostgresDbExists(options: any, root: string): Promise<true> {
    // Use require.resolve to find the package, which handles npm workspace hoisting
    const pgPath = require.resolve('pg', { paths: [root] });
    const { Client } = await import(pgPath);
    const connectionOptions = {
        host: options.host,
        user: options.username,
        password: options.password,
        port: options.port,
        database: options.database,
        schema: options.schema,
        ssl: options.ssl,
    };
    const client = new Client(connectionOptions);

    try {
        await client.connect();

        const schema = await client.query(
            `SELECT schema_name
             FROM information_schema.schemata
             WHERE schema_name = '${options.schema as string}'`,
        );
        if (schema.rows.length === 0) {
            throw new Error('NO_SCHEMA');
        }
    } catch (e: any) {
        if (e.code === '3D000') {
            throwDatabaseDoesNotExist(options.database);
        } else if (e.message === 'NO_SCHEMA') {
            throwDatabaseSchemaDoesNotExist(options.database, options.schema);
        } else if (e.code === '28000') {
            throwSSLConnectionError(e, options.ssl);
        }
        throwConnectionError(e);
        await client.end();
        throw e;
    }
    await client.end();
    return true;
}

/**
 * Check to see if Docker is installed and running.
 * If not, attempt to start it.
 * If that is not possible, return false.
 *
 * Refs:
 * - https://stackoverflow.com/a/48843074/772859
 */
export async function isDockerAvailable(): Promise<{ result: 'not-found' | 'not-running' | 'running' }> {
    const dockerSpinner = spinner();

    function isDaemonRunning(): boolean {
        try {
            execFileSync('docker', ['stats', '--no-stream'], { stdio: 'ignore' });
            return true;
        } catch (e: any) {
            return false;
        }
    }

    dockerSpinner.start('Checking for Docker');
    try {
        execFileSync('docker', ['-v'], { stdio: 'ignore' });
        dockerSpinner.message('Docker was found!');
    } catch (e: any) {
        dockerSpinner.stop('Docker was not found on this machine. We will use SQLite for the database.');
        return { result: 'not-found' };
    }
    // Now we need to check if the docker daemon is running
    const isRunning = isDaemonRunning();
    if (isRunning) {
        dockerSpinner.stop('Docker is running');
        return { result: 'running' };
    }
    dockerSpinner.message('Docker daemon is not running. Attempting to start');
    // detect the current OS
    const currentPlatform = platform();
    try {
        if (currentPlatform === 'win32') {
            // https://stackoverflow.com/a/44182489/772859
            execSync('"C:\\Program Files\\Docker\\Docker\\Docker Desktop.exe"', { stdio: 'ignore' });
        } else if (currentPlatform === 'darwin') {
            execSync('open -a Docker', { stdio: 'ignore' });
        } else {
            execSync('systemctl start docker', { stdio: 'ignore' });
        }
    } catch (e: any) {
        dockerSpinner.stop('Could not start Docker.');
        log(e.message, { level: 'verbose' });
        return { result: 'not-running' };
    }
    // Verify that the daemon is now running
    let attempts = 1;
    do {
        log(`Checking for Docker daemon... (attempt ${attempts})`, { level: 'verbose' });
        if (isDaemonRunning()) {
            log(`Docker daemon is now running (after ${attempts} attempts).`, { level: 'verbose' });
            dockerSpinner.stop('Docker is running');
            return { result: 'running' };
        }
        await new Promise(resolve => setTimeout(resolve, 50));
        attempts++;
    } while (attempts < 100);
    dockerSpinner.stop('Docker daemon could not be started');
    return { result: 'not-running' };
}

/**
 * Sanitizes a project name into a valid Docker Compose project name
 * (lowercase letters, digits, `-` and `_`, starting with an alphanumeric).
 * Used as the top-level `name` in the generated docker-compose.yml so that each
 * created project gets its own Compose project. Without it, Compose derives the
 * project name from the compose file's directory — which in monorepo mode is
 * always `apps/server`, so every project would collide on the project "server".
 *
 * When sanitization alters the name, a stable suffix derived from the original is
 * appended: otherwise distinct project names could sanitize to the same value
 * (e.g. `shop.v1` and `shopv1`) and end up sharing containers and volumes.
 */
export function toComposeProjectName(name: string): string {
    const sanitized = name
        .toLowerCase()
        .replace(/[^a-z0-9_-]+/g, '-')
        .replace(/^[_-]+/, '');
    if (sanitized === name) {
        return name;
    }
    const suffix = createHash('sha256').update(name).digest('hex').slice(0, 8);
    const base = sanitized.replace(/[_-]+$/, '') || 'vendure';
    return `${base}-${suffix}`;
}

export async function startPostgresDatabase(root: string, projectName: string): Promise<boolean> {
    // Now we need to run the postgres database via Docker
    let containerName: string | undefined;
    const postgresContainerSpinner = spinner();
    postgresContainerSpinner.start('Starting PostgreSQL database');
    try {
        const composePromise = promisify(execFile)(`docker`, [
            `compose`,
            `-f`,
            path.join(root, 'docker-compose.yml'),
            `up`,
            `-d`,
            `postgres_db`,
        ]);
        // `docker compose up` can ask interactive questions (e.g. "Volume exists but
        // doesn't match configuration. Recreate?"). Close stdin so it gets EOF instead
        // of blocking forever on a prompt the user cannot see.
        composePromise.child.stdin?.end();
        const result = await composePromise;
        containerName = result.stderr.match(/Container\s+(.+-postgres_db[^ ]*)/)?.[1];
        if (!containerName) {
            // Fall back to Compose's naming convention: <project>-<service>-<index>
            containerName = `${toComposeProjectName(projectName)}-postgres_db-1`;
            postgresContainerSpinner.message(
                'Could not find container name. Guessing it is: ' + containerName,
            );
            log(pc.red('Could not find container name. Guessing it is: ' + containerName), {
                newline: 'before',
                level: 'verbose',
            });
        } else {
            log(pc.green(`Started PostgreSQL database in container "${containerName}"`), {
                newline: 'before',
                level: 'verbose',
            });
        }
    } catch (e: any) {
        log(pc.red(`Failed to start PostgreSQL database: ${e.message as string}`));
        postgresContainerSpinner.stop('Failed to start PostgreSQL database');
        return false;
    }
    postgresContainerSpinner.message(`Waiting for PostgreSQL database to be ready...`);
    let attempts = 1;
    let isReady = false;
    do {
        // We now need to ensure that the database is ready to accept connections.
        // The `-h localhost` forces a TCP check: during a first boot, initdb runs a
        // temporary server that only listens on the unix socket, and a socket-based
        // pg_isready would report "ready" before the real server is up.
        try {
            const result = execFileSync(`docker`, [
                `exec`,
                `-i`,
                containerName,
                `pg_isready`,
                `-h`,
                `localhost`,
            ]);
            isReady = result?.toString().includes('accepting connections');
            if (!isReady) {
                log(pc.yellow(`PostgreSQL database not yet ready. Attempt ${attempts}...`), {
                    level: 'verbose',
                });
            }
        } catch (e: any) {
            // ignore
            log('is_ready error:' + (e.message as string), { level: 'verbose', newline: 'before' });
        }
        if (isReady) {
            break;
        }
        await new Promise(resolve => setTimeout(resolve, PG_READY_POLL_INTERVAL_MS));
        attempts++;
    } while (attempts <= PG_READY_MAX_ATTEMPTS);
    if (!isReady) {
        postgresContainerSpinner.stop(
            pc.red(
                `PostgreSQL database did not become ready within ${Math.round(
                    (PG_READY_MAX_ATTEMPTS * PG_READY_POLL_INTERVAL_MS) / 1000,
                )} seconds`,
            ),
        );
        log(`Check the container logs with: docker logs ${containerName}`);
        return false;
    }
    postgresContainerSpinner.stop('PostgreSQL database is ready');
    return true;
}

function throwConnectionError(err: any) {
    throw new Error(
        'Could not connect to the database. ' +
            `Please check the connection settings in your Vendure config.\n[${
                (err.message || err.toString()) as string
            }]`,
    );
}

function throwSSLConnectionError(err: any, sslEnabled?: any) {
    throw new Error(
        'Could not connect to the database. ' +
            (sslEnabled === undefined
                ? 'Is your server requiring an SSL connection?'
                : 'Are you sure your server supports SSL?') +
            `Please check the connection settings in your Vendure config.\n[${
                (err.message || err.toString()) as string
            }]`,
    );
}

function throwDatabaseDoesNotExist(name: string) {
    throw new Error(`Database "${name}" does not exist. Please create the database and then try again.`);
}

function throwDatabaseSchemaDoesNotExist(dbName: string, schemaName: string) {
    throw new Error(
        `Schema "${dbName}.${schemaName}" does not exist. Please create the schema "${schemaName}" and then try again.`,
    );
}

/**
 * Returns `true` if the given TCP port on `127.0.0.1` is already bound, `false`
 * if the port is free. Rejects on invalid port input or on any socket error
 * other than `ECONNREFUSED` — surfacing the real error (e.g. `EACCES`,
 * `EHOSTUNREACH`) to the caller rather than silently treating it as "in use"
 * and letting a port scan exhaust before reporting a misleading message.
 */
export function isServerPortInUse(port: number): Promise<boolean> {
    if (!Number.isInteger(port) || port < 1 || port > 65535) {
        return Promise.reject(new Error(`Invalid port: ${port}`));
    }
    return new Promise((resolve, reject) => {
        const client = new Socket();
        let settled = false;
        const cleanup = () => {
            client.removeAllListeners();
            client.destroy();
        };
        // Node can emit `error` after `close`, and on some platforms an `error` may follow a
        // successful `connect`. Guarding every handler with this flag means only the first
        // outcome decides the promise.
        const settle = (): boolean => {
            if (settled) return false;
            settled = true;
            cleanup();
            return true;
        };
        client.setTimeout(SOCKET_TIMEOUT_MS);
        client.once('connect', () => {
            if (!settle()) return;
            resolve(true);
        });
        client.once('timeout', () => {
            if (!settle()) return;
            reject(new Error(`Timed out checking port ${port} after ${SOCKET_TIMEOUT_MS}ms`));
        });
        client.once('error', (err: NodeJS.ErrnoException) => {
            if (!settle()) return;
            if (err.code === 'ECONNREFUSED') {
                resolve(false);
                return;
            }
            log(
                pc.yellow(
                    `Warning: could not determine whether port ${port} is available (${
                        err.code ?? err.message
                    })`,
                ),
            );
            reject(err);
        });
        client.connect({ port, host: '127.0.0.1' });
    });
}

/**
 * Checks if the response from a Clack prompt was a cancellation symbol, and if so,
 * ends the interactive process.
 */
export function checkCancel<T>(value: T | symbol): value is T {
    if (isCancel(value)) {
        cancel('Setup cancelled.');
        process.exit(0);
    }
    return true;
}

export function cleanUpDockerResources(name: string) {
    const labelFilter = `label=io.vendure.create.name=${name}`;
    const listIds = (args: string[]): string[] =>
        execFileSync('docker', args)
            .toString()
            .split('\n')
            .map(line => line.trim())
            .filter(Boolean);
    try {
        const containerIds = listIds(['ps', '-a', '-q', '--filter', labelFilter]);
        if (containerIds.length) {
            execFileSync('docker', ['stop', ...containerIds], { stdio: 'ignore' });
            execFileSync('docker', ['rm', ...containerIds], { stdio: 'ignore' });
        }
        const volumeIds = listIds(['volume', 'ls', '-q', '--filter', labelFilter]);
        if (volumeIds.length) {
            execFileSync('docker', ['volume', 'rm', ...volumeIds], { stdio: 'ignore' });
        }
    } catch (e) {
        log(pc.yellow(`Could not clean up Docker resources`), { level: 'verbose' });
    }
}

export function resolvePackageRootDir(packageName: string, rootDir: string) {
    let packageEntryPath: string;
    try {
        packageEntryPath = require.resolve(packageName, { paths: [rootDir] });
    } catch {
        log(`Falling back to direct node_modules lookup for ${packageName}`);
        const fallbackPath = path.join(process.cwd(), 'node_modules', packageName);
        if (fs.existsSync(fallbackPath)) {
            return fallbackPath;
        }
        throw new Error(
            `Cannot resolve package "${packageName}" (checked in ${fallbackPath}). Is it installed?`,
        );
    }

    const target = packageName.split('/').pop();
    let dir = path.dirname(packageEntryPath);
    const root = path.parse(dir).root;

    while (path.basename(dir) !== target) {
        const next = path.dirname(dir);
        if (next === dir || dir === root) {
            throw new Error(`Could not locate package root for "${packageName}" from "${packageEntryPath}".`);
        }
        dir = next;
    }
    return dir;
}

/**
 * Downloads the Next.js storefront starter from GitHub and extracts it to the target directory.
 * Uses the GitHub API tarball endpoint to avoid requiring git.
 */
export async function downloadAndExtractStorefront(targetDir: string): Promise<void> {
    const tarballUrl = `https://api.github.com/repos/${STOREFRONT_REPO}/tarball/${STOREFRONT_BRANCH}`;
    const tempTarPath = path.join(targetDir, '..', 'storefront-temp.tar.gz');

    try {
        // Fetch the tarball from GitHub. A token (e.g. in CI) raises the rate limit.
        const response = await fetch(tarballUrl, {
            headers: {
                Accept: 'application/vnd.github+json',
                'User-Agent': 'vendure-create',
                ...(process.env.GITHUB_TOKEN ? { Authorization: `Bearer ${process.env.GITHUB_TOKEN}` } : {}),
            },
        });

        if (!response.ok) {
            throw new Error(`Failed to download storefront: ${response.status} ${response.statusText}`);
        }

        // Save the tarball to a temp file
        const fileStream = createWriteStream(tempTarPath);
        // Convert the web ReadableStream to a Node.js Readable stream
        const nodeReadable = Readable.fromWeb(response.body as import('node:stream/web').ReadableStream);
        await pipeline(nodeReadable, fileStream);

        // Create target directory
        await fs.ensureDir(targetDir);

        // Extract the tarball
        await tar.extract({
            file: tempTarPath,
            cwd: targetDir,
            strip: 1, // Remove the top-level directory from the archive
        });

        // Clean up temp file
        await fs.remove(tempTarPath);
    } catch (error) {
        // Clean up on error
        await fs.remove(tempTarPath).catch(() => {
            // eslint-disable-next-line
            console.error(error);
        });
        throw error;
    }
}

/**
 * Finds an available port starting from the given port.
 * Returns the first available port within the specified range.
 */
export async function findAvailablePort(startPort: number, range: number = 20): Promise<number> {
    let port = startPort;
    while (true) {
        let inUse: boolean;
        try {
            inUse = await isServerPortInUse(port);
        } catch (e) {
            throw new Error(`Could not probe port ${port}: ${e instanceof Error ? e.message : String(e)}`);
        }
        if (!inUse) return port;
        port++;
        if (port > startPort + range) {
            throw new Error(`Could not find an available port between ${startPort} and ${startPort + range}`);
        }
    }
}
